=== qyslamd/ETestStudio/资料收集/Schema/IcdSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- edited with XMLSpy v2011 (http://www.altova.com) by JianLuo (Microsoft) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="ICDData">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Name" type="xs:string"/>
				<xs:element name="Data" type="ICDWords"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="ICDWord">
		<xs:sequence>
			<xs:element name="Offset" type="xs:int"/>
			<xs:element name="StartBit" type="xs:int"/>
			<xs:element name="BitWidth" type="xs:int"/>
			<xs:element name="Type" type="xs:string"/>
			<xs:element name="Name" type="xs:string">
				<xs:annotation>
					<xs:documentation>信号名称</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Description" type="xs:string">
				<xs:annotation>
					<xs:documentation>物理信号名称</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="GroupName" type="xs:string" minOccurs="0"/>
			<xs:element name="IsScaled" type="xs:int">
				<xs:annotation>
					<xs:documentation>0/1</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="ScaleA" type="xs:double" minOccurs="0"/>
			<xs:element name="ScaleB" type="xs:double" minOccurs="0"/>
			<xs:element name="Childs" type="ICDWords" minOccurs="0"/>
			<xs:element name="SystemName" type="xs:string" minOccurs="0"/>
			<xs:element name="Min" type="xs:double" minOccurs="0"/>
			<xs:element name="Max" type="xs:double" minOccurs="0"/>
			<xs:element name="Unit" type="xs:string" minOccurs="0"/>
			<xs:element name="Tag" type="xs:int" minOccurs="0"/>
			<xs:element name="ValueTextList" type="xs:string" minOccurs="0"/>
			<xs:element name="ScaleFormula" type="xs:string" default="" minOccurs="0"/>
			<xs:element name="ScaleConveror" type="xs:string" default="" minOccurs="0"/>
			<xs:element name="DefauleValue" minOccurs="0"/>
			<xs:element name="LinkTo" type="xs:string" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ICDWords">
		<xs:sequence maxOccurs="unbounded">
			<xs:element name="Item" type="ICDWord"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== qyslamd/ETestStudio/资料收集/Schema/A429_00_ISI_01_发送_Label174_6272T_00.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<ICDData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="IcdSchema.xsd">
	<Name/>
	<Data>
		<Item>
			<Offset>0</Offset>
			<StartBit>0</StartBit>
			<BitWidth>32</BitWidth>
			<Type>dword</Type>
			<Name>ISI-01#A429_IN1(174) 发送数据</Name>
			<Description>发送的32位数据</Description>
			<GroupName>ISI-01#A429_OUT1(174)</GroupName>
			<IsScaled>0</IsScaled>
			<Childs>
				<Item>
					<Offset>0</Offset>
					<StartBit>0</StartBit>
					<BitWidth>8</BitWidth>
					<Type>byte</Type>
					<Name>ISI-01#A429_IN1(174) LABEL</Name>
					<Description>8bit有效,八进制,174</Description>
					<GroupName>ISI-01#A429_OUT1(174)</GroupName>
					<IsScaled>0</IsScaled>
					<SystemName>Arinc429</SystemName>
					<Tag>40</Tag>
					<ValueTextList>124</ValueTextList>
					<LinkTo>\6272T_00\ch0</LinkTo>
				</Item>
				<Item>
					<Offset>1</Offset>
					<StartBit>0</StartBit>
					<BitWidth>2</BitWidth>
					<Type>byte</Type>
					<Name>ISI-01#A429_IN1(174) SDI</Name>
					<Description>2bit有效,内容:不用=0,左单元=1,右单元=2,中间单元=3</Description>
					<GroupName>ISI-01#A429_OUT1(174)</GroupName>
					<IsScaled>0</IsScaled>
					<SystemName>Arinc429</SystemName>
					<Tag>0</Tag>
					<ValueTextList>不用=0,左单元=1,右单元=2,中间单元=3</ValueTextList>
					<LinkTo>\6272T_00\ch0</LinkTo>
				</Item>
				<Item>
					<Offset>1</Offset>
					<StartBit>2</StartBit>
					<BitWidth>3</BitWidth>
					<Type>byte</Type>
					<Name>ISI-01#A429_IN1(174) PAD</Name>
					<Description>3bit有效</Description>
					<GroupName>ISI-01#A429_OUT1(174)</GroupName>
					<IsScaled>0</IsScaled>
					<SystemName>Arinc429</SystemName>
					<Tag>0</Tag>
					<ValueTextList>0</ValueTextList>
					<LinkTo>\6272T_00\ch0</LinkTo>
				</Item>
				<Item>
					<Offset>1</Offset>
					<StartBit>5</StartBit>
					<BitWidth>16</BitWidth>
					<Type>int</Type>
					<Name>ISI-01#A429_IN1(174) East_or_West_Velocity（GNSS）</Name>
					<Description>垂直偏差,16bit有效,范围:-4096~4095.875,0=正（东）,1= 负(西)</Description>
					<GroupName>ISI-01#A429_OUT1(174)</GroupName>
					<IsScaled>1</IsScaled>
					<ScaleA>0.125</ScaleA>
					<SystemName>Arinc429</SystemName>
					<Unit>节</Unit>
					<Tag>0</Tag>
					<ValueTextList>0</ValueTextList>
					<LinkTo>\6272T_00\ch0</LinkTo>
				</Item>
				<Item>
					<Offset>3</Offset>
					<StartBit>5</StartBit>
					<BitWidth>2</BitWidth>
					<Type>byte</Type>
					<Name>ISI-01#A429_IN1(174) SSM</Name>
					<Description>2bit有效,内容:Failure_Warning=0,No_Computed_Data=1,Functional_Test=2,Normal_Operation=3</Description>
					<GroupName>ISI-01#A429_OUT1(174)</GroupName>
					<IsScaled>0</IsScaled>
					<SystemName>Arinc429</SystemName>
					<Tag>0</Tag>
					<ValueTextList>Failure_Warning=0,No_Computed_Data=1,Functional_Test=2,Normal_Operation=3</ValueTextList>
					<LinkTo>\6272T_00\ch0</LinkTo>
				</Item>
				<Item>
					<Offset>3</Offset>
					<StartBit>7</StartBit>
					<BitWidth>1</BitWidth>
					<Type>byte</Type>
					<Name>ISI-01#A429_IN1(174) PARITY</Name>
					<Description>1bit有效,Set to obtain odd word parity</Description>
					<GroupName>ISI-01#A429_OUT1(174)</GroupName>
					<IsScaled>0</IsScaled>
					<SystemName>Arinc429</SystemName>
					<Tag>0</Tag>
					<ValueTextList>0</ValueTextList>
					<LinkTo>\6272T_00\ch0</LinkTo>
				</Item>
			</Childs>
			<SystemName>Arinc429</SystemName>
		</Item>
	</Data>
</ICDData>

=== qyslamd/ETestStudio/资料收集/Schema/A429_00_ISI_01_发送_Label111_5272_00.xml
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<ICDData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="IcdSchema.xsd">
	<Name/>
	<Data>
		<Item>
			<Offset>0</Offset>
			<StartBit>0</StartBit>
			<BitWidth>32</BitWidth>
			<Type>dword</Type>
			<Name>ISI-01#A429_IN1(111) 发送数据</Name>
			<Description>发送的32位数据</Description>
			<GroupName>ISI-01#A429_IN1(111)</GroupName>
			<IsScaled>0</IsScaled>
			<Childs>
				<Item>
					<Offset>0</Offset>
					<StartBit>0</StartBit>
					<BitWidth>8</BitWidth>
					<Type>byte</Type>
					<Name>ISI-01#A429_IN1(111) LABEL</Name>
					<Description>8bit有效,八进制,111</Description>
					<GroupName>ISI-01#A429_IN1(111)</GroupName>
					<IsScaled>0</IsScaled>
					<SystemName>Arinc429</SystemName>
					<Tag>40</Tag>
					<ValueTextList>73</ValueTextList>
					<LinkTo>5272_00\ch0</LinkTo>
				</Item>
				<Item>
					<Offset>1</Offset>
					<StartBit>0</StartBit>
					<BitWidth>21</BitWidth>
					<Type>int</Type>
					<Name>ISI-01#A429_IN1(111) GNSS_Longitude</Name>
					<Description>21bit有效,范围:-180~179.9998283</Description>
					<GroupName>ISI-01#A429_IN1(111)</GroupName>
					<IsScaled>1</IsScaled>
					<ScaleA>0.000171661376953125</ScaleA>
					<SystemName>Arinc429</SystemName>
					<Unit>°</Unit>
					<Tag>0</Tag>
					<ValueTextList>0</ValueTextList>
					<LinkTo>5272_00\ch0</LinkTo>
				</Item>
				<Item>
					<Offset>3</Offset>
					<StartBit>5</StartBit>
					<BitWidth>2</BitWidth>
					<Type>byte</Type>
					<Name>ISI-01#A429_IN1(111) SSM</Name>
					<Description>2bit有效,内容:Failure_Warning=0,No_Computed_Data=1,Functional_Test=2,Normal_Operation=3</Description>
					<GroupName>ISI-01#A429_IN1(111)</GroupName>
					<IsScaled>0</IsScaled>
					<SystemName>Arinc429</SystemName>
					<Tag>0</Tag>
					<ValueTextList>Failure_Warning=0,No_Computed_Data=1,Functional_Test=2,Normal_Operation=3</ValueTextList>
					<LinkTo>5272_00\ch0</LinkTo>
				</Item>
				<Item>
					<Offset>3</Offset>
					<StartBit>7</StartBit>
					<BitWidth>1</BitWidth>
					<Type>byte</Type>
					<Name>ISI-01#A429_IN1(111) PARITY</Name>
					<Description>1bit有效,Set to obtain odd word parity</Description>
					<GroupName>ISI-01#A429_IN1(111)</GroupName>
					<IsScaled>0</IsScaled>
					<SystemName>Arinc429</SystemName>
					<Tag>0</Tag>
					<ValueTextList>0</ValueTextList>
					<LinkTo>5272_00\ch0</LinkTo>
				</Item>
			</Childs>
			<SystemName>Arinc429</SystemName>
		</Item>
	</Data>
</ICDData>

=== qyslamd/ETestStudio/docs/02-研究/Schema/A429_03_ISI_01_发送_Label273_5272_03.xml
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<<<<<<< HEAD
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
=======
>>>>>>> 65a49280ce73fa5643f132301f9d69071d289295
<ICDData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="IcdSchema.xsd">
	<Name/>
	<Data>
		<Item>
			<Offset>0</Offset>
			<StartBit>0</StartBit>
			<BitWidth>32</BitWidth>
			<Type>dword</Type>
			<Name>ISI-01#A429_IN4(273) 发送数据</Name>
			<Description>发送的32位数据</Description>
			<GroupName>ISI-01#A429_IN4(273)</GroupName>
			<IsScaled>0</IsScaled>
			<Childs>
				<Item>
					<Offset>0</Offset>
					<StartBit>0</StartBit>
					<BitWidth>8</BitWidth>
					<Type>byte</Type>
					<Name>ISI-01#A429_IN4(273) LABEL</Name>
					<Description>8bit有效,八进制,273</Description>
					<GroupName>ISI-01#A429_IN4(273)</GroupName>
					<IsScaled>0</IsScaled>
					<SystemName>Arinc429</SystemName>
					<Tag>40</Tag>
					<ValueTextList>187</ValueTextList>
					<LinkTo>5272_03\ch3</LinkTo>
				</Item>
				<Item>
					<Offset>1</Offset>
					<StartBit>0</StartBit>
					<BitWidth>2</BitWidth>
					<Type>byte</Type>
					<Name>ISI-01#A429_IN4(273) SDI</Name>
					<Description>2bit有效,SOURCE/Destination Identifier</Description>
					<GroupName>ISI-01#A429_IN4(273)</GroupName>
					<IsScaled>0</IsScaled>
					<SystemName>Arinc429</SystemName>
					<Tag>0</Tag>
					<ValueTextList>0</ValueTextList>
					<LinkTo>5272_03\ch3</LinkTo>
				</Item>
				<Item>
					<Offset>1</Offset>
					<StartBit>2</StartBit>
					<BitWidth>19</BitWidth>
					<Type>int</Type>
					<Name>ISI-01#A429_IN4(273) NLG_Dnlocked</Name>
					<Description>19bit有效</Description>
					<GroupName>ISI-01#A429_IN4(273)</GroupName>
					<IsScaled>0</IsScaled>
					<SystemName>Arinc429</SystemName>
					<Min>-262144</Min>
					<Max>262143</Max>
					<Tag>0</Tag>
					<ValueTextList>0</ValueTextList>
					<LinkTo>5272_03\ch3</LinkTo>
				</Item>
				<Item>
					<Offset>3</Offset>
					<StartBit>5</StartBit>
					<BitWidth>2</BitWidth>
					<Type>byte</Type>
					<Name>ISI-01#A429_IN4(273) SSM</Name>
					<Description>2bit有效,Sign/Status Matrix</Description>
					<GroupName>ISI-01#A429_IN4(273)</GroupName>
					<IsScaled>0</IsScaled>
					<SystemName>Arinc429</SystemName>
					<Tag>0</Tag>
					<ValueTextList>0</ValueTextList>
					<LinkTo>5272_03\ch3</LinkTo>
				</Item>
				<Item>
					<Offset>3</Offset>
					<StartBit>7</StartBit>
					<BitWidth>1</BitWidth>
					<Type>byte</Type>
					<Name>ISI-01#A429_IN4(273) Parity</Name>
					<Description>1bit有效,Set to obtain odd word parity</Description>
					<GroupName>ISI-01#A429_IN4(273)</GroupName>
					<IsScaled>0</IsScaled>
					<SystemName>Arinc429</SystemName>
					<Tag>0</Tag>
					<ValueTextList>0</ValueTextList>
					<LinkTo>5272_03\ch3</LinkTo>
				</Item>
			</Childs>
			<SystemName>Arinc429</SystemName>
		</Item>
	</Data>
</ICDData>

=== qyslamd/ETestStudio/资料收集/Schema/A429_00_ISI_01_接收_Label260_6272T_00.xml
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<ICDData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="IcdSchema.xsd">
	<Name/>
	<Data>
		<Item>
			<Offset>0</Offset>
			<StartBit>0</StartBit>
			<BitWidth>32</BitWidth>
			<Type>dword</Type>
			<Name>ISI-01#A429_OUT(260) 接收数据</Name>
			<Description>接收的32位数据</Description>
			<GroupName>ISI-01#A429_IN(260)</GroupName>
			<IsScaled>0</IsScaled>
			<Childs>
				<Item>
					<Offset>0</Offset>
					<StartBit>0</StartBit>
					<BitWidth>8</BitWidth>
					<Type>byte</Type>
					<Name>ISI-01#A429_OUT(260) LABEL</Name>
					<Description>8bit有效,八进制,260</Description>
					<GroupName>ISI-01#A429_IN(260)</GroupName>
					<IsScaled>0</IsScaled>
					<SystemName>Arinc429</SystemName>
					<Tag>40</Tag>
					<ValueTextList>176</ValueTextList>
					<LinkTo>\6272T_00\ch0</LinkTo>
				</Item>
				<Item>
					<Offset>1</Offset>
					<StartBit>0</StartBit>
					<BitWidth>2</BitWidth>
					<Type>byte</Type>
					<Name>ISI-01#A429_OUT(260) SDI</Name>
					<Description>2bit有效,内容:Not_Used=0,Left_GNSS=1,Right_GNSS=2,Not_Used=3</Description>
					<GroupName>ISI-01#A429_IN(260)</GroupName>
					<IsScaled>0</IsScaled>
					<SystemName>Arinc429</SystemName>
					<Tag>0</Tag>
					<ValueTextList>Not_Used1=0,Left_GNSS=1,Right_GNSS=2,Not_Used2=3</ValueTextList>
					<LinkTo>\6272T_00\ch0</LinkTo>
				</Item>
				<Item>
					<Offset>1</Offset>
					<StartBit>2</StartBit>
					<BitWidth>4</BitWidth>
					<Type>byte</Type>
					<Name>ISI-01#A429_OUT(260) Date_Year_Ones_Digit</Name>
					<Description>4bit有效</Description>
					<GroupName>ISI-01#A429_IN(260)</GroupName>
					<IsScaled>0</IsScaled>
					<SystemName>Arinc429</SystemName>
					<Tag>0</Tag>
					<ValueTextList>0</ValueTextList>
					<LinkTo>\6272T_00\ch0</LinkTo>
				</Item>
				<Item>
					<Offset>1</Offset>
					<StartBit>6</StartBit>
					<BitWidth>4</BitWidth>
					<Type>byte</Type>
					<Name>ISI-01#A429_OUT(260) Date_Year_Tens_Digit</Name>
					<Description>4bit有效</Description>
					<GroupName>ISI-01#A429_IN(260)</GroupName>
					<IsScaled>0</IsScaled>
					<SystemName>Arinc429</SystemName>
					<Tag>0</Tag>
					<ValueTextList>0</ValueTextList>
					<LinkTo>\6272T_00\ch0</LinkTo>
				</Item>
				<Item>
					<Offset>2</Offset>
					<StartBit>2</StartBit>
					<BitWidth>4</BitWidth>
					<Type>byte</Type>
					<Name>ISI-01#A429_OUT(260) Month_Ones_Digit</Name>
					<Description>4bit有效</Description>
					<GroupName>ISI-01#A429_IN(260)</GroupName>
					<IsScaled>0</IsScaled>
					<SystemName>Arinc429</SystemName>
					<Tag>0</Tag>
					<ValueTextList>0</ValueTextList>
					<LinkTo>\6272T_00\ch0</LinkTo>
				</Item>
				<Item>
					<Offset>2</Offset>
					<StartBit>6</StartBit>
					<BitWidth>1</BitWidth>
					<Type>byte</Type>
					<Name>ISI-01#A429_OUT(260) Month_Tens_Digit</Name>
					<Description>1bit有效</Description>
					<GroupName>ISI-01#A429_IN(260)</GroupName>
					<IsScaled>0</IsScaled>
					<SystemName>Arinc429</SystemName>
					<Tag>0</Tag>
					<ValueTextList>0</ValueTextList>
					<LinkTo>\6272T_00\ch0</LinkTo>
				</Item>
				<Item>
					<Offset>2</Offset>
					<StartBit>7</StartBit>
					<BitWidth>4</BitWidth>
					<Type>byte</Type>
					<Name>ISI-01#A429_OUT(260) Day_Ones_Digit</Name>
					<Description>4bit有效</Description>
					<GroupName>ISI-01#A429_IN(260)</GroupName>
					<IsScaled>0</IsScaled>
					<SystemName>Arinc429</SystemName>
					<Tag>0</Tag>
					<ValueTextList>0</ValueTextList>
					<LinkTo>\6272T_00\ch0</LinkTo>
				</Item>
				<Item>
					<Offset>3</Offset>
					<StartBit>3</StartBit>
					<BitWidth>2</BitWidth>
					<Type>byte</Type>
					<Name>ISI-01#A429_OUT(260) Day_Tens_Digit</Name>
					<Description>2bit有效</Description>
					<GroupName>ISI-01#A429_IN(260)</GroupName>
					<IsScaled>0</IsScaled>
					<SystemName>Arinc429</SystemName>
					<Tag>0</Tag>
					<ValueTextList>0</ValueTextList>
					<LinkTo>\6272T_00\ch0</LinkTo>
				</Item>
				<Item>
					<Offset>3</Offset>
					<StartBit>5</StartBit>
					<BitWidth>2</BitWidth>
					<Type>byte</Type>
					<Name>ISI-01#A429_OUT(260) SSM</Name>
					<Description>2bit有效</Description>
					<GroupName>ISI-01#A429_IN(260)</GroupName>
					<IsScaled>0</IsScaled>
					<SystemName>Arinc429</SystemName>
					<Tag>0</Tag>
					<ValueTextList>0</ValueTextList>
					<LinkTo>\6272T_00\ch0</LinkTo>
				</Item>
				<Item>
					<Offset>3</Offset>
					<StartBit>7</StartBit>
					<BitWidth>1</BitWidth>
					<Type>byte</Type>
					<Name>ISI-01#A429_OUT(260) PARITY</Name>
					<Description>1bit有效</Description>
					<GroupName>ISI-01#A429_IN(260)</GroupName>
					<IsScaled>0</IsScaled>
					<SystemName>Arinc429</SystemName>
					<Tag>0</Tag>
					<ValueTextList>0</ValueTextList>
					<LinkTo>\6272T_00\ch0</LinkTo>
				</Item>
			</Childs>
			<SystemName>Arinc429</SystemName>
		</Item>
	</Data>
</ICDData>

=== qyslamd/ETestStudio/docs/资料收集/Schema/A429_03_ISI_01_发送_Label317_6272T_03.xml
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<ICDData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="IcdSchema.xsd">
	<Name/>
	<Data>
		<Item>
			<Offset>0</Offset>
			<StartBit>0</StartBit>
			<BitWidth>32</BitWidth>
			<Type>dword</Type>
			<Name>ISI-01#A429_IN4(317) 发送数据</Name>
			<Description>发送的32位数据</Description>
			<GroupName>ISI-01#A429_OUT4(317)</GroupName>
			<IsScaled>0</IsScaled>
			<Childs>
				<Item>
					<Offset>0</Offset>
					<StartBit>0</StartBit>
					<BitWidth>8</BitWidth>
					<Type>byte</Type>
					<Name>ISI-01#A429_IN4(317) LABEL</Name>
					<Description>8bit有效,八进制,317</Description>
					<GroupName>ISI-01#A429_OUT4(317)</GroupName>
					<IsScaled>0</IsScaled>
					<SystemName>Arinc429</SystemName>
					<Tag>40</Tag>
					<ValueTextList>207</ValueTextList>
					<LinkTo>\6272T_03\ch3</LinkTo>
				</Item>
				<Item>
					<Offset>1</Offset>
					<StartBit>0</StartBit>
					<BitWidth>2</BitWidth>
					<Type>byte</Type>
					<Name>ISI-01#A429_IN4(317) SDI</Name>
					<Description>2bit有效,内容:无=0,IRU_1=1,IRU_2=2,IRU_3=3</Description>
					<GroupName>ISI-01#A429_OUT4(317)</GroupName>
					<IsScaled>0</IsScaled>
					<SystemName>Arinc429</SystemName>
					<Tag>0</Tag>
					<ValueTextList>无=0,IRU_1=1,IRU_2=2,IRU_3=3</ValueTextList>
					<LinkTo>\6272T_03\ch3</LinkTo>
				</Item>
				<Item>
					<Offset>1</Offset>
					<StartBit>2</StartBit>
					<BitWidth>19</BitWidth>
					<Type>int</Type>
					<Name>ISI-01#A429_IN4(317) Magnetic_Track_Angle</Name>
					<Description>19bit有效,±180</Description>
					<GroupName>ISI-01#A429_OUT4(317)</GroupName>
					<IsScaled>1</IsScaled>
					<ScaleA>0.000687</ScaleA>
					<SystemName>Arinc429</SystemName>
					<Unit>°</Unit>
					<Tag>0</Tag>
					<ValueTextList>0</ValueTextList>
					<LinkTo>\6272T_03\ch3</LinkTo>
				</Item>
				<Item>
					<Offset>3</Offset>
					<StartBit>5</StartBit>
					<BitWidth>2</BitWidth>
					<Type>byte</Type>
					<Name>ISI-01#A429_IN4(317) SSM</Name>
					<Description>2bit有效,Sign/Status Matrix</Description>
					<GroupName>ISI-01#A429_OUT4(317)</GroupName>
					<IsScaled>0</IsScaled>
					<SystemName>Arinc429</SystemName>
					<Tag>0</Tag>
					<ValueTextList>0</ValueTextList>
					<LinkTo>\6272T_03\ch3</LinkTo>
				</Item>
				<Item>
					<Offset>3</Offset>
					<StartBit>7</StartBit>
					<BitWidth>1</BitWidth>
					<Type>byte</Type>
					<Name>ISI-01#A429_IN4(317) Parity</Name>
					<Description>1bit有效,Set to obtain odd word parity</Description>
					<GroupName>ISI-01#A429_OUT4(317)</GroupName>
					<IsScaled>0</IsScaled>
					<SystemName>Arinc429</SystemName>
					<Tag>0</Tag>
					<ValueTextList>0</ValueTextList>
					<LinkTo>\6272T_03\ch3</LinkTo>
				</Item>
			</Childs>
			<SystemName>Arinc429</SystemName>
		</Item>
	</Data>
</ICDData>

=== qyslamd/ETestStudio/资料收集/Schema/A429_01_ISI_01_配置_5272_01.xml
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<ICDData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="IcdSchema.xsd">
	<Name/>
	<Data>
		<Item>
			<Offset>0</Offset>
			<StartBit>0</StartBit>
			<BitWidth>16</BitWidth>
			<Type>word</Type>
			<Name>ISI-01#A429_01 校验方式</Name>
			<Description>无=0，奇校验=1，偶校验=2</Description>
			<GroupName>ISI-01#A429_01</GroupName>
			<IsScaled>0</IsScaled>
			<SystemName>Arinc429</SystemName>
			<Tag>0</Tag>
			<ValueTextList>无,奇校验,偶校验</ValueTextList>
			<LinkTo>\5272_01\ch1</LinkTo>
		</Item>
		<Item>
			<Offset>2</Offset>
			<StartBit>0</StartBit>
			<BitWidth>16</BitWidth>
			<Type>word</Type>
			<Name>ISI-01#A429_01 发送周期</Name>
			<Description>帧间隔时间，支持 1-65535ms。默认1000ms。</Description>
			<GroupName>ISI-01#A429_01</GroupName>
			<IsScaled>0</IsScaled>
			<SystemName>Arinc429</SystemName>
			<Unit>ms</Unit>
			<Tag>0</Tag>
			<ValueTextList>1000</ValueTextList>
			<LinkTo>\5272_01\ch1</LinkTo>
		</Item>
		<Item>
			<Offset>4</Offset>
			<StartBit>0</StartBit>
			<BitWidth>16</BitWidth>
			<Type>word</Type>
			<Name>ISI-01#A429_01 波特率</Name>
			<Description>波特率设置值，100K=0,50K=1,48K=2,12.5K=3</Description>
			<GroupName>ISI-01#A429_01</GroupName>
			<IsScaled>0</IsScaled>
			<SystemName>Arinc429</SystemName>
			<Tag>0</Tag>
			<ValueTextList>100K=0,50K=1,48K=2,12.5K=3</ValueTextList>
			<LinkTo>\5272_01\ch1</LinkTo>
		</Item>
	</Data>
</ICDData>

=== qyslamd/ETestStudio/docs/资料收集/Schema/A429_02_ISI_01_配置_6272T_10.xml
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<ICDData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="IcdSchema.xsd">
	<Name/>
	<Data>
		<Item>
			<Offset>0</Offset>
			<StartBit>0</StartBit>
			<BitWidth>16</BitWidth>
			<Type>word</Type>
<<<<<<< HEAD
			<Name>ISI-01#A429_02 校验方式</Name>
			<Description>无=0，奇校验=1，偶校验=2</Description>
			<GroupName>ISI-01#A429_02</GroupName>
=======
			<Name>ISI-01#A429_10 校验方式</Name>
			<Description>无=0，奇校验=1，偶校验=2</Description>
			<GroupName>ISI-01#A429_10</GroupName>
>>>>>>> 65a49280ce73fa5643f132301f9d69071d289295
			<IsScaled>0</IsScaled>
			<SystemName>ARINC429总线通讯模块</SystemName>
			<Tag>0</Tag>
			<ValueTextList>无,奇校验,偶校验</ValueTextList>
			<LinkTo>\6272T_10\ch10</LinkTo>
		</Item>
		<Item>
			<Offset>2</Offset>
			<StartBit>0</StartBit>
			<BitWidth>16</BitWidth>
			<Type>word</Type>
<<<<<<< HEAD
			<Name>ISI-01#A429_02 发送周期</Name>
			<Description>帧间隔时间，支持 1-65535ms。默认1000ms。</Description>
			<GroupName>ISI-01#A429_02</GroupName>
=======
			<Name>ISI-01#A429_10 发送周期</Name>
			<Description>帧间隔时间，支持 1-65535ms。默认1000ms。</Description>
			<GroupName>ISI-01#A429_10</GroupName>
>>>>>>> 65a49280ce73fa5643f132301f9d69071d289295
			<IsScaled>0</IsScaled>
			<SystemName>ARINC429总线通讯模块</SystemName>
			<Unit>ms</Unit>
			<Tag>0</Tag>
			<ValueTextList>1000</ValueTextList>
			<LinkTo>\6272T_10\ch10</LinkTo>
		</Item>
		<Item>
			<Offset>4</Offset>
			<StartBit>0</StartBit>
			<BitWidth>16</BitWidth>
			<Type>word</Type>
<<<<<<< HEAD
			<Name>ISI-01#A429_02 波特率</Name>
			<Description>波特率设置值，100K=0,50K=1,48K=2,12.5K=3</Description>
			<GroupName>ISI-01#A429_02</GroupName>
=======
			<Name>ISI-01#A429_10 波特率</Name>
			<Description>波特率设置值，100K=0,50K=1,48K=2,12.5K=3</Description>
			<GroupName>ISI-01#A429_10</GroupName>
>>>>>>> 65a49280ce73fa5643f132301f9d69071d289295
			<IsScaled>0</IsScaled>
			<SystemName>ARINC429总线通讯模块</SystemName>
			<Tag>0</Tag>
			<ValueTextList>100K=0,50K=1,48K=2,12.5K=3</ValueTextList>
			<LinkTo>\6272T_10\ch10</LinkTo>
		</Item>
	</Data>
</ICDData>

=== qyslamd/ETestStudio/资料收集/Schema/摄像头_控制指令_LanTLIPC342_0.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<ICDData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="IcdSchema.xsd">
	<Name/>
	<Data>
		<Item>
			<Offset>0</Offset>
			<StartBit>0</StartBit>
			<BitWidth>32</BitWidth>
			<Type>dword</Type>
			<Name>高清摄像头 截图指令</Name>
			<Description>截图</Description>
			<GroupName>高清摄像头</GroupName>
			<IsScaled>0</IsScaled>
			<SystemName>高清摄像头</SystemName>
			<Tag>0</Tag>
			<ValueTextList>0</ValueTextList>
			<LinkTo>\LanTLIPC342_0\ch0</LinkTo>
		</Item>
		<Item>
			<Offset>4</Offset>
			<StartBit>0</StartBit>
			<BitWidth>32</BitWidth>
			<Type>dword</Type>
			<Name>高清摄像头 录像指令</Name>
			<Description>0:停止录制，1：开始录制</Description>
			<GroupName>高清摄像头</GroupName>
			<IsScaled>0</IsScaled>
			<SystemName>高清摄像头</SystemName>
			<Tag>0</Tag>
			<ValueTextList>停止录制=0,开始录制=1</ValueTextList>
			<LinkTo>\LanTLIPC342_0\ch0</LinkTo>
		</Item>
		<Item>
			<Offset>8</Offset>
			<StartBit>0</StartBit>
			<BitWidth>2080</BitWidth>
			<Type>string</Type>
			<Name>高清摄像头 截图路径</Name>
			<Description>截图路径</Description>
			<GroupName>高清摄像头</GroupName>
			<IsScaled>0</IsScaled>
			<SystemName>高清摄像头</SystemName>
			<Tag>0</Tag>
			<LinkTo>\LanTLIPC342_0\ch0</LinkTo>
		</Item>
		<Item>
			<Offset>268</Offset>
			<StartBit>0</StartBit>
			<BitWidth>2080</BitWidth>
			<Type>string</Type>
			<Name>高清摄像头 录像路径</Name>
			<Description>录像路径</Description>
			<GroupName>高清摄像头</GroupName>
			<IsScaled>0</IsScaled>
			<SystemName>高清摄像头</SystemName>
			<Tag>0</Tag>
			<LinkTo>\LanTLIPC342_0\ch0</LinkTo>
		</Item>
	</Data>
</ICDData>
