=== qyslamd/ETestStudio/资料收集/Schema/IcdSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- edited with XMLSpy v2011 (http://www.altova.com) by JianLuo (Microsoft) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="ICDData">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Name" type="xs:string"/>
				<xs:element name="Data" type="ICDWords"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="ICDWord">
		<xs:sequence>
			<xs:element name="Offset" type="xs:int"/>
			<xs:element name="StartBit" type="xs:int"/>
			<xs:element name="BitWidth" type="xs:int"/>
			<xs:element name="Type" type="xs:string"/>
			<xs:element name="Name" type="xs:string">
				<xs:annotation>
					<xs:documentation>信号名称</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Description" type="xs:string">
				<xs:annotation>
					<xs:documentation>物理信号名称</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="GroupName" type="xs:string" minOccurs="0"/>
			<xs:element name="IsScaled" type="xs:int">
				<xs:annotation>
					<xs:documentation>0/1</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="ScaleA" type="xs:double" minOccurs="0"/>
			<xs:element name="ScaleB" type="xs:double" minOccurs="0"/>
			<xs:element name="Childs" type="ICDWords" minOccurs="0"/>
			<xs:element name="SystemName" type="xs:string" minOccurs="0"/>
			<xs:element name="Min" type="xs:double" minOccurs="0"/>
			<xs:element name="Max" type="xs:double" minOccurs="0"/>
			<xs:element name="Unit" type="xs:string" minOccurs="0"/>
			<xs:element name="Tag" type="xs:int" minOccurs="0"/>
			<xs:element name="ValueTextList" type="xs:string" minOccurs="0"/>
			<xs:element name="ScaleFormula" type="xs:string" default="" minOccurs="0"/>
			<xs:element name="ScaleConveror" type="xs:string" default="" minOccurs="0"/>
			<xs:element name="DefauleValue" minOccurs="0"/>
			<xs:element name="LinkTo" type="xs:string" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ICDWords">
		<xs:sequence maxOccurs="unbounded">
			<xs:element name="Item" type="ICDWord"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== qyslamd/ETestStudio/docs/资料收集/Schema/A429_00_ISI_01_接收_Label162_6272T_00.xml
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<ICDData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="IcdSchema.xsd">
	<Name/>
	<Data>
		<Item>
			<Offset>0</Offset>
			<StartBit>0</StartBit>
			<BitWidth>32</BitWidth>
			<Type>dword</Type>
			<Name>ISI-01#A429_OUT(162) 接收数据</Name>
			<Description>接收的32位数据</Description>
			<GroupName>ISI-01#A429_IN(162)</GroupName>
			<IsScaled>0</IsScaled>
			<Childs>
				<Item>
					<Offset>0</Offset>
					<StartBit>0</StartBit>
					<BitWidth>8</BitWidth>
					<Type>byte</Type>
					<Name>ISI-01#A429_OUT(162) LABEL</Name>
					<Description>8bit有效,八进制,162</Description>
					<GroupName>ISI-01#A429_IN(162)</GroupName>
					<IsScaled>0</IsScaled>
					<SystemName>Arinc429</SystemName>
					<Tag>40</Tag>
					<ValueTextList>114</ValueTextList>
					<LinkTo>\6272T_00\ch0</LinkTo>
				</Item>
				<Item>
					<Offset>1</Offset>
					<StartBit>0</StartBit>
					<BitWidth>4</BitWidth>
					<Type>byte</Type>
					<Name>ISI-01#A429_OUT(162) re1</Name>
					<Description>4bit</Description>
					<IsScaled>0</IsScaled>
					<Tag>0</Tag>
					<ValueTextList>0</ValueTextList>
					<LinkTo>\6272T_00\ch0</LinkTo>
				</Item>
				<Item>
					<Offset>1</Offset>
					<StartBit>4</StartBit>
					<BitWidth>17</BitWidth>
					<Type>int</Type>
					<Name>ISI-01#A429_OUT(162) FIX_Distance</Name>
					<Description>17bit有效,范围:0~6553.5</Description>
					<GroupName>ISI-01#A429_IN(162)</GroupName>
					<IsScaled>1</IsScaled>
					<ScaleA>0.1</ScaleA>
					<SystemName>Arinc429</SystemName>
					<Unit>NM</Unit>
					<Tag>0</Tag>
					<ValueTextList>0</ValueTextList>
					<LinkTo>\6272T_00\ch0</LinkTo>
				</Item>
				<Item>
					<Offset>3</Offset>
					<StartBit>5</StartBit>
					<BitWidth>2</BitWidth>
					<Type>byte</Type>
					<Name>ISI-01#A429_OUT(162) SSM</Name>
					<Description>2bit有效</Description>
					<GroupName>ISI-01#A429_IN(162)</GroupName>
					<IsScaled>0</IsScaled>
					<SystemName>Arinc429</SystemName>
					<Tag>0</Tag>
					<ValueTextList>0</ValueTextList>
					<LinkTo>\6272T_00\ch0</LinkTo>
				</Item>
				<Item>
					<Offset>3</Offset>
					<StartBit>7</StartBit>
					<BitWidth>1</BitWidth>
					<Type>byte</Type>
					<Name>ISI-01#A429_OUT(162) PARITY</Name>
					<Description>1bit有效</Description>
					<GroupName>ISI-01#A429_IN(162)</GroupName>
					<IsScaled>0</IsScaled>
					<SystemName>Arinc429</SystemName>
					<Tag>0</Tag>
					<ValueTextList>0</ValueTextList>
					<LinkTo>\6272T_00\ch0</LinkTo>
				</Item>
			</Childs>
			<SystemName>Arinc429</SystemName>
		</Item>
	</Data>
</ICDData>

=== qyslamd/ETestStudio/资料收集/Schema/A429_00_ISI_01_接收_Label331_5272_00.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<ICDData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="IcdSchema.xsd">
	<Name/>
	<Data>
		<Item>
			<Offset>0</Offset>
			<StartBit>0</StartBit>
			<BitWidth>32</BitWidth>
			<Type>dword</Type>
			<Name>ISI-01#A429_OUT(331) 接收数据</Name>
			<Description>接收的32位数据</Description>
			<GroupName>ISI-01#A429_OUT(331)</GroupName>
			<IsScaled>0</IsScaled>
			<Childs>
				<Item>
					<Offset>0</Offset>
					<StartBit>0</StartBit>
					<BitWidth>8</BitWidth>
					<Type>byte</Type>
					<Name>ISI-01#A429_OUT(331) LABEL</Name>
					<Description>8bit有效,八进制,331</Description>
					<GroupName>ISI-01#A429_OUT(331)</GroupName>
					<IsScaled>0</IsScaled>
					<SystemName>Arinc429</SystemName>
					<Tag>40</Tag>
					<ValueTextList>217</ValueTextList>
					<LinkTo>5272_00\ch0</LinkTo>
				</Item>
				<Item>
					<Offset>1</Offset>
					<StartBit>0</StartBit>
					<BitWidth>2</BitWidth>
					<Type>byte</Type>
					<Name>ISI-01#A429_OUT(331) SDI</Name>
					<Description>2bit有效,内容:ISIS=0</Description>
					<GroupName>ISI-01#A429_OUT(331)</GroupName>
					<IsScaled>0</IsScaled>
					<SystemName>Arinc429</SystemName>
					<Tag>0</Tag>
					<ValueTextList>ISIS=0</ValueTextList>
					<LinkTo>5272_00\ch0</LinkTo>
				</Item>
				<Item>
					<Offset>1</Offset>
					<StartBit>2</StartBit>
					<BitWidth>3</BitWidth>
					<Type>byte</Type>
					<Name>ISI-01#A429_OUT(331) PAD</Name>
					<Description>3bit有效</Description>
					<GroupName>ISI-01#A429_OUT(331)</GroupName>
					<IsScaled>0</IsScaled>
					<SystemName>Arinc429</SystemName>
					<Tag>0</Tag>
					<ValueTextList>0</ValueTextList>
					<LinkTo>5272_00\ch0</LinkTo>
				</Item>
				<Item>
					<Offset>1</Offset>
					<StartBit>5</StartBit>
					<BitWidth>16</BitWidth>
					<Type>int</Type>
					<Name>ISI-01#A429_OUT(331) Longitudinal_Accel</Name>
					<Description>16bit有效,范围:-20~19.99941832</Description>
					<GroupName>ISI-01#A429_OUT(331)</GroupName>
					<IsScaled>1</IsScaled>
					<ScaleA>0.000610352</ScaleA>
					<SystemName>Arinc429</SystemName>
					<Min>0</Min>
					<Max>0</Max>
					<Unit>G</Unit>
					<Tag>0</Tag>
					<ValueTextList>0</ValueTextList>
					<LinkTo>5272_00\ch0</LinkTo>
				</Item>
				<Item>
					<Offset>3</Offset>
					<StartBit>5</StartBit>
					<BitWidth>2</BitWidth>
					<Type>byte</Type>
					<Name>ISI-01#A429_OUT(331) SSM</Name>
					<Description>2bit有效,内容:Not_Used1=0,Not_Used2=1,Not_Used3=2,Normal_Operation=3</Description>
					<GroupName>ISI-01#A429_OUT(331)</GroupName>
					<IsScaled>0</IsScaled>
					<SystemName>Arinc429</SystemName>
					<Tag>0</Tag>
					<ValueTextList>Not_Used1=0,Not_Used2=1,Not_Used3=2,Normal_Operation=3</ValueTextList>
					<LinkTo>5272_00\ch0</LinkTo>
				</Item>
				<Item>
					<Offset>3</Offset>
					<StartBit>7</StartBit>
					<BitWidth>1</BitWidth>
					<Type>byte</Type>
					<Name>ISI-01#A429_OUT(331) PARITY</Name>
					<Description>1bit有效</Description>
					<GroupName>ISI-01#A429_OUT(331)</GroupName>
					<IsScaled>0</IsScaled>
					<SystemName>Arinc429</SystemName>
					<Tag>0</Tag>
					<ValueTextList>0</ValueTextList>
					<LinkTo>5272_00\ch0</LinkTo>
				</Item>
			</Childs>
			<SystemName>Arinc429</SystemName>
		</Item>
	</Data>
</ICDData>

=== qyslamd/ETestStudio/资料收集/Schema/串口自检_发送_5276H_00_COM6.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<ICDData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="IcdSchema.xsd">
	<Name/>
	<Data>
		<Item>
			<Offset>0</Offset>
			<StartBit>0</StartBit>
			<BitWidth>16</BitWidth>
			<Type>word</Type>
			<Name>串口通道00 发送_帧头</Name>
			<Description>帧头，0xAA55 = 43605</Description>
			<GroupName>串口通道00</GroupName>
			<IsScaled>0</IsScaled>
			<SystemName>串口</SystemName>
			<Tag>1</Tag>
			<ValueTextList>43605</ValueTextList>
			<LinkTo>\5276H_00_COM6\ch6</LinkTo>
		</Item>
		<Item>
			<Offset>2</Offset>
			<StartBit>0</StartBit>
			<BitWidth>8</BitWidth>
			<Type>byte</Type>
			<Name>串口通道00 发送_Byte0</Name>
			<Description>字节，byte0</Description>
			<GroupName>串口通道00</GroupName>
			<IsScaled>0</IsScaled>
			<SystemName>串口</SystemName>
			<Tag>0</Tag>
			<ValueTextList>0</ValueTextList>
			<LinkTo>\5276H_00_COM6\ch6</LinkTo>
		</Item>
		<Item>
			<Offset>3</Offset>
			<StartBit>0</StartBit>
			<BitWidth>8</BitWidth>
			<Type>byte</Type>
			<Name>串口通道00 发送_Byte1</Name>
			<Description>字节，byte1</Description>
			<GroupName>串口通道00</GroupName>
			<IsScaled>0</IsScaled>
			<SystemName>串口</SystemName>
			<Tag>0</Tag>
			<ValueTextList>1</ValueTextList>
			<LinkTo>\5276H_00_COM6\ch6</LinkTo>
		</Item>
		<Item>
			<Offset>4</Offset>
			<StartBit>0</StartBit>
			<BitWidth>8</BitWidth>
			<Type>byte</Type>
			<Name>串口通道00 发送_Byte2</Name>
			<Description>字节，byte2</Description>
			<GroupName>串口通道00</GroupName>
			<IsScaled>0</IsScaled>
			<SystemName>串口</SystemName>
			<Tag>0</Tag>
			<ValueTextList>2</ValueTextList>
			<LinkTo>\5276H_00_COM6\ch6</LinkTo>
		</Item>
		<Item>
			<Offset>5</Offset>
			<StartBit>0</StartBit>
			<BitWidth>8</BitWidth>
			<Type>byte</Type>
			<Name>串口通道00 发送_Byte3</Name>
			<Description>字节，byte3</Description>
			<GroupName>串口通道00</GroupName>
			<IsScaled>0</IsScaled>
			<SystemName>串口</SystemName>
			<Tag>0</Tag>
			<ValueTextList>3</ValueTextList>
			<LinkTo>\5276H_00_COM6\ch6</LinkTo>
		</Item>
		<Item>
			<Offset>6</Offset>
			<StartBit>0</StartBit>
			<BitWidth>8</BitWidth>
			<Type>byte</Type>
			<Name>串口通道00 发送_Byte4</Name>
			<Description>字节，byte4</Description>
			<GroupName>串口通道00</GroupName>
			<IsScaled>0</IsScaled>
			<SystemName>串口</SystemName>
			<Tag>0</Tag>
			<ValueTextList>4</ValueTextList>
			<LinkTo>\5276H_00_COM6\ch6</LinkTo>
		</Item>
		<Item>
			<Offset>7</Offset>
			<StartBit>0</StartBit>
			<BitWidth>8</BitWidth>
			<Type>byte</Type>
			<Name>串口通道00 发送_Byte5</Name>
			<Description>字节，byte5</Description>
			<GroupName>串口通道00</GroupName>
			<IsScaled>0</IsScaled>
			<SystemName>串口</SystemName>
			<Tag>0</Tag>
			<ValueTextList>5</ValueTextList>
			<LinkTo>\5276H_00_COM6\ch6</LinkTo>
		</Item>
		<Item>
			<Offset>8</Offset>
			<StartBit>0</StartBit>
			<BitWidth>8</BitWidth>
			<Type>byte</Type>
			<Name>串口通道00 发送_Byte6</Name>
			<Description>字节，byte6</Description>
			<GroupName>串口通道00</GroupName>
			<IsScaled>0</IsScaled>
			<SystemName>串口</SystemName>
			<Tag>0</Tag>
			<ValueTextList>6</ValueTextList>
			<LinkTo>\5276H_00_COM6\ch6</LinkTo>
		</Item>
		<Item>
			<Offset>9</Offset>
			<StartBit>0</StartBit>
			<BitWidth>8</BitWidth>
			<Type>byte</Type>
			<Name>串口通道00 发送_Byte7</Name>
			<Description>字节，byte7</Description>
			<GroupName>串口通道00</GroupName>
			<IsScaled>0</IsScaled>
			<SystemName>串口</SystemName>
			<Tag>0</Tag>
			<ValueTextList>7</ValueTextList>
			<LinkTo>\5276H_00_COM6\ch6</LinkTo>
		</Item>
		<Item>
			<Offset>10</Offset>
			<StartBit>0</StartBit>
			<BitWidth>8</BitWidth>
			<Type>byte</Type>
			<Name>串口通道00 发送_Byte8</Name>
			<Description>字节，byte8</Description>
			<GroupName>串口通道00</GroupName>
			<IsScaled>0</IsScaled>
			<SystemName>串口</SystemName>
			<Tag>0</Tag>
			<ValueTextList>8</ValueTextList>
			<LinkTo>\5276H_00_COM6\ch6</LinkTo>
		</Item>
		<Item>
			<Offset>11</Offset>
			<StartBit>0</StartBit>
			<BitWidth>8</BitWidth>
			<Type>byte</Type>
			<Name>串口通道00 发送_Byte9</Name>
			<Description>字节，byte9</Description>
			<GroupName>串口通道00</GroupName>
			<IsScaled>0</IsScaled>
			<SystemName>串口</SystemName>
			<Tag>0</Tag>
			<ValueTextList>9</ValueTextList>
			<LinkTo>\5276H_00_COM6\ch6</LinkTo>
		</Item>
		<Item>
			<Offset>12</Offset>
			<StartBit>0</StartBit>
			<BitWidth>8</BitWidth>
			<Type>byte</Type>
			<Name>串口通道00 发送_Byte10</Name>
			<Description>字节，byte10</Description>
			<GroupName>串口通道00</GroupName>
			<IsScaled>0</IsScaled>
			<SystemName>串口</SystemName>
			<Tag>0</Tag>
			<ValueTextList>10</ValueTextList>
			<LinkTo>\5276H_00_COM6\ch6</LinkTo>
		</Item>
		<Item>
			<Offset>13</Offset>
			<StartBit>0</StartBit>
			<BitWidth>8</BitWidth>
			<Type>byte</Type>
			<Name>串口通道00 发送_Byte11</Name>
			<Description>字节，byte11</Description>
			<GroupName>串口通道00</GroupName>
			<IsScaled>0</IsScaled>
			<SystemName>串口</SystemName>
			<Tag>0</Tag>
			<ValueTextList>11</ValueTextList>
			<LinkTo>\5276H_00_COM6\ch6</LinkTo>
		</Item>
		<Item>
			<Offset>14</Offset>
			<StartBit>0</StartBit>
			<BitWidth>8</BitWidth>
			<Type>byte</Type>
			<Name>串口通道00 发送_Byte12</Name>
			<Description>字节，byte12</Description>
			<GroupName>串口通道00</GroupName>
			<IsScaled>0</IsScaled>
			<SystemName>串口</SystemName>
			<Tag>0</Tag>
			<ValueTextList>12</ValueTextList>
			<LinkTo>\5276H_00_COM6\ch6</LinkTo>
		</Item>
		<Item>
			<Offset>15</Offset>
			<StartBit>0</StartBit>
			<BitWidth>8</BitWidth>
			<Type>byte</Type>
			<Name>串口通道00 发送_Byte13</Name>
			<Description>字节，byte13</Description>
			<GroupName>串口通道00</GroupName>
			<IsScaled>0</IsScaled>
			<SystemName>串口</SystemName>
			<Tag>0</Tag>
			<ValueTextList>13</ValueTextList>
			<LinkTo>\5276H_00_COM6\ch6</LinkTo>
		</Item>
		<Item>
			<Offset>16</Offset>
			<StartBit>0</StartBit>
			<BitWidth>8</BitWidth>
			<Type>byte</Type>
			<Name>串口通道00 发送_Byte14</Name>
			<Description>字节，byte14</Description>
			<GroupName>串口通道00</GroupName>
			<IsScaled>0</IsScaled>
			<SystemName>串口</SystemName>
			<Tag>0</Tag>
			<ValueTextList>14</ValueTextList>
			<LinkTo>\5276H_00_COM6\ch6</LinkTo>
		</Item>
		<Item>
			<Offset>17</Offset>
			<StartBit>0</StartBit>
			<BitWidth>8</BitWidth>
			<Type>byte</Type>
			<Name>串口通道00 发送_Byte15</Name>
			<Description>字节，byte15</Description>
			<GroupName>串口通道00</GroupName>
			<IsScaled>0</IsScaled>
			<SystemName>串口</SystemName>
			<Tag>0</Tag>
			<ValueTextList>15</ValueTextList>
			<LinkTo>\5276H_00_COM6\ch6</LinkTo>
		</Item>
		<Item>
			<Offset>18</Offset>
			<StartBit>0</StartBit>
			<BitWidth>8</BitWidth>
			<Type>byte</Type>
			<Name>串口通道00 发送_Byte16</Name>
			<Description>字节，byte16</Description>
			<GroupName>串口通道00</GroupName>
			<IsScaled>0</IsScaled>
			<SystemName>串口</SystemName>
			<Tag>0</Tag>
			<ValueTextList>16</ValueTextList>
			<LinkTo>\5276H_00_COM6\ch6</LinkTo>
		</Item>
		<Item>
			<Offset>19</Offset>
			<StartBit>0</StartBit>
			<BitWidth>8</BitWidth>
			<Type>byte</Type>
			<Name>串口通道00 发送_Byte17</Name>
			<Description>字节，byte17</Description>
			<GroupName>串口通道00</GroupName>
			<IsScaled>0</IsScaled>
			<SystemName>串口</SystemName>
			<Tag>0</Tag>
			<ValueTextList>17</ValueTextList>
			<LinkTo>\5276H_00_COM6\ch6</LinkTo>
		</Item>
	</Data>
</ICDData>

=== qyslamd/ETestStudio/docs/02-研究/Schema/5V导光板电源_接收设定电压电流_ComCHH50W_COM11.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<ICDData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="IcdSchema.xsd">
	<Name/>
	<Data>
		<Item>
			<Offset>0</Offset>
			<StartBit>0</StartBit>
			<BitWidth>8</BitWidth>
			<Type>byte</Type>
			<Name>byte0</Name>
			<Description>默认为1</Description>
			<IsScaled>0</IsScaled>
			<Tag>40</Tag>
			<ValueTextList>1</ValueTextList>
			<LinkTo>\ComCHH50W_COM11\ch11</LinkTo>
		</Item>
		<Item>
			<Offset>1</Offset>
			<StartBit>0</StartBit>
			<BitWidth>8</BitWidth>
			<Type>byte</Type>
			<Name>byte1</Name>
			<Description>默认为3</Description>
			<IsScaled>0</IsScaled>
			<Tag>40</Tag>
			<ValueTextList>3</ValueTextList>
			<LinkTo>\ComCHH50W_COM11\ch11</LinkTo>
		</Item>
		<Item>
			<Offset>2</Offset>
			<StartBit>0</StartBit>
			<BitWidth>8</BitWidth>
			<Type>byte</Type>
			<Name>byte2</Name>
			<Description>默认为0x4</Description>
			<IsScaled>0</IsScaled>
			<Tag>40</Tag>
			<ValueTextList>4</ValueTextList>
			<LinkTo>\ComCHH50W_COM11\ch11</LinkTo>
		</Item>
		<Item>
			<Offset>3</Offset>
			<StartBit>0</StartBit>
			<BitWidth>16</BitWidth>
			<Type>word</Type>
			<Name>5V导光板电源 获取电压设定值</Name>
			<Description>仅此项是大端，单位为V，分辨率为0.01</Description>
			<GroupName>5V导光板电源</GroupName>
			<IsScaled>1</IsScaled>
			<ScaleA>0.01</ScaleA>
			<SystemName>5V导光板电源</SystemName>
			<Unit>V</Unit>
			<Tag>41</Tag>
			<ValueTextList>0</ValueTextList>
			<LinkTo>\ComCHH50W_COM11\ch11</LinkTo>
		</Item>
		<Item>
			<Offset>5</Offset>
			<StartBit>0</StartBit>
			<BitWidth>16</BitWidth>
			<Type>word</Type>
			<Name>5V导光板电源 获取电流设定值</Name>
			<Description>仅此项是大端，单位为A，分辨率为0.01</Description>
			<GroupName>5V导光板电源</GroupName>
			<IsScaled>1</IsScaled>
			<ScaleA>0.01</ScaleA>
			<SystemName>5V导光板电源</SystemName>
			<Unit>A</Unit>
			<Tag>41</Tag>
			<ValueTextList>0</ValueTextList>
			<LinkTo>\ComCHH50W_COM11\ch11</LinkTo>
		</Item>
		<Item>
			<Offset>7</Offset>
			<StartBit>0</StartBit>
			<BitWidth>16</BitWidth>
			<Type>word</Type>
			<Name>CRC校验</Name>
			<Description>crc校验，小端</Description>
			<IsScaled>0</IsScaled>
			<Tag>0</Tag>
			<ValueTextList>0</ValueTextList>
			<LinkTo>\ComCHH50W_COM11\ch11</LinkTo>
		</Item>
	</Data>
</ICDData>

=== qyslamd/ETestStudio/docs/02-研究/Schema/串口自检_接收_6276K8_07_COM14.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<ICDData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="IcdSchema.xsd">
	<Name/>
	<Data>
		<Item>
			<Offset>0</Offset>
			<StartBit>0</StartBit>
			<BitWidth>16</BitWidth>
			<Type>word</Type>
			<Name>串口通道07 接收_帧头</Name>
			<Description>帧头，0xAA55 = 43605</Description>
			<GroupName>串口通道07</GroupName>
			<IsScaled>0</IsScaled>
			<SystemName>串口</SystemName>
			<Tag>1</Tag>
			<ValueTextList>43605</ValueTextList>
			<LinkTo>\6276K8_07_COM14\ch14</LinkTo>
		</Item>
		<Item>
			<Offset>2</Offset>
			<StartBit>0</StartBit>
			<BitWidth>8</BitWidth>
			<Type>byte</Type>
			<Name>串口通道07 接收_Byte0</Name>
			<Description>字节，byte0</Description>
			<GroupName>串口通道07</GroupName>
			<IsScaled>0</IsScaled>
			<SystemName>串口</SystemName>
			<Tag>0</Tag>
			<ValueTextList>0</ValueTextList>
			<LinkTo>\6276K8_07_COM14\ch14</LinkTo>
		</Item>
		<Item>
			<Offset>3</Offset>
			<StartBit>0</StartBit>
			<BitWidth>8</BitWidth>
			<Type>byte</Type>
			<Name>串口通道07 接收_Byte1</Name>
			<Description>字节，byte1</Description>
			<GroupName>串口通道07</GroupName>
			<IsScaled>0</IsScaled>
			<SystemName>串口</SystemName>
			<Tag>0</Tag>
			<ValueTextList>0</ValueTextList>
			<LinkTo>\6276K8_07_COM14\ch14</LinkTo>
		</Item>
		<Item>
			<Offset>4</Offset>
			<StartBit>0</StartBit>
			<BitWidth>8</BitWidth>
			<Type>byte</Type>
			<Name>串口通道07 接收_Byte2</Name>
			<Description>字节，byte2</Description>
			<GroupName>串口通道07</GroupName>
			<IsScaled>0</IsScaled>
			<SystemName>串口</SystemName>
			<Tag>0</Tag>
			<ValueTextList>0</ValueTextList>
			<LinkTo>\6276K8_07_COM14\ch14</LinkTo>
		</Item>
		<Item>
			<Offset>5</Offset>
			<StartBit>0</StartBit>
			<BitWidth>8</BitWidth>
			<Type>byte</Type>
			<Name>串口通道07 接收_Byte3</Name>
			<Description>字节，byte3</Description>
			<GroupName>串口通道07</GroupName>
			<IsScaled>0</IsScaled>
			<SystemName>串口</SystemName>
			<Tag>0</Tag>
			<ValueTextList>0</ValueTextList>
			<LinkTo>\6276K8_07_COM14\ch14</LinkTo>
		</Item>
		<Item>
			<Offset>6</Offset>
			<StartBit>0</StartBit>
			<BitWidth>8</BitWidth>
			<Type>byte</Type>
			<Name>串口通道07 接收_Byte4</Name>
			<Description>字节，byte4</Description>
			<GroupName>串口通道07</GroupName>
			<IsScaled>0</IsScaled>
			<SystemName>串口</SystemName>
			<Tag>0</Tag>
			<ValueTextList>0</ValueTextList>
			<LinkTo>\6276K8_07_COM14\ch14</LinkTo>
		</Item>
		<Item>
			<Offset>7</Offset>
			<StartBit>0</StartBit>
			<BitWidth>8</BitWidth>
			<Type>byte</Type>
			<Name>串口通道07 接收_Byte5</Name>
			<Description>字节，byte5</Description>
			<GroupName>串口通道07</GroupName>
			<IsScaled>0</IsScaled>
			<SystemName>串口</SystemName>
			<Tag>0</Tag>
			<ValueTextList>0</ValueTextList>
			<LinkTo>\6276K8_07_COM14\ch14</LinkTo>
		</Item>
		<Item>
			<Offset>8</Offset>
			<StartBit>0</StartBit>
			<BitWidth>8</BitWidth>
			<Type>byte</Type>
			<Name>串口通道07 接收_Byte6</Name>
			<Description>字节，byte6</Description>
			<GroupName>串口通道07</GroupName>
			<IsScaled>0</IsScaled>
			<SystemName>串口</SystemName>
			<Tag>0</Tag>
			<ValueTextList>0</ValueTextList>
			<LinkTo>\6276K8_07_COM14\ch14</LinkTo>
		</Item>
		<Item>
			<Offset>9</Offset>
			<StartBit>0</StartBit>
			<BitWidth>8</BitWidth>
			<Type>byte</Type>
			<Name>串口通道07 接收_Byte7</Name>
			<Description>字节，byte7</Description>
			<GroupName>串口通道07</GroupName>
			<IsScaled>0</IsScaled>
			<SystemName>串口</SystemName>
			<Tag>0</Tag>
			<ValueTextList>0</ValueTextList>
			<LinkTo>\6276K8_07_COM14\ch14</LinkTo>
		</Item>
		<Item>
			<Offset>10</Offset>
			<StartBit>0</StartBit>
			<BitWidth>8</BitWidth>
			<Type>byte</Type>
			<Name>串口通道07 接收_Byte8</Name>
			<Description>字节，byte8</Description>
			<GroupName>串口通道07</GroupName>
			<IsScaled>0</IsScaled>
			<SystemName>串口</SystemName>
			<Tag>0</Tag>
			<ValueTextList>0</ValueTextList>
			<LinkTo>\6276K8_07_COM14\ch14</LinkTo>
		</Item>
		<Item>
			<Offset>11</Offset>
			<StartBit>0</StartBit>
			<BitWidth>8</BitWidth>
			<Type>byte</Type>
			<Name>串口通道07 接收_Byte9</Name>
			<Description>字节，byte9</Description>
			<GroupName>串口通道07</GroupName>
			<IsScaled>0</IsScaled>
			<SystemName>串口</SystemName>
			<Tag>0</Tag>
			<ValueTextList>0</ValueTextList>
			<LinkTo>\6276K8_07_COM14\ch14</LinkTo>
		</Item>
		<Item>
			<Offset>12</Offset>
			<StartBit>0</StartBit>
			<BitWidth>8</BitWidth>
			<Type>byte</Type>
			<Name>串口通道07 接收_Byte10</Name>
			<Description>字节，byte10</Description>
			<GroupName>串口通道07</GroupName>
			<IsScaled>0</IsScaled>
			<SystemName>串口</SystemName>
			<Tag>0</Tag>
			<ValueTextList>0</ValueTextList>
			<LinkTo>\6276K8_07_COM14\ch14</LinkTo>
		</Item>
		<Item>
			<Offset>13</Offset>
			<StartBit>0</StartBit>
			<BitWidth>8</BitWidth>
			<Type>byte</Type>
			<Name>串口通道07 接收_Byte11</Name>
			<Description>字节，byte11</Description>
			<GroupName>串口通道07</GroupName>
			<IsScaled>0</IsScaled>
			<SystemName>串口</SystemName>
			<Tag>0</Tag>
			<ValueTextList>0</ValueTextList>
			<LinkTo>\6276K8_07_COM14\ch14</LinkTo>
		</Item>
		<Item>
			<Offset>14</Offset>
			<StartBit>0</StartBit>
			<BitWidth>8</BitWidth>
			<Type>byte</Type>
			<Name>串口通道07 接收_Byte12</Name>
			<Description>字节，byte12</Description>
			<GroupName>串口通道07</GroupName>
			<IsScaled>0</IsScaled>
			<SystemName>串口</SystemName>
			<Tag>0</Tag>
			<ValueTextList>0</ValueTextList>
			<LinkTo>\6276K8_07_COM14\ch14</LinkTo>
		</Item>
		<Item>
			<Offset>15</Offset>
			<StartBit>0</StartBit>
			<BitWidth>8</BitWidth>
			<Type>byte</Type>
			<Name>串口通道07 接收_Byte13</Name>
			<Description>字节，byte13</Description>
			<GroupName>串口通道07</GroupName>
			<IsScaled>0</IsScaled>
			<SystemName>串口</SystemName>
			<Tag>0</Tag>
			<ValueTextList>0</ValueTextList>
			<LinkTo>\6276K8_07_COM14\ch14</LinkTo>
		</Item>
		<Item>
			<Offset>16</Offset>
			<StartBit>0</StartBit>
			<BitWidth>8</BitWidth>
			<Type>byte</Type>
			<Name>串口通道07 接收_Byte14</Name>
			<Description>字节，byte14</Description>
			<GroupName>串口通道07</GroupName>
			<IsScaled>0</IsScaled>
			<SystemName>串口</SystemName>
			<Tag>0</Tag>
			<ValueTextList>0</ValueTextList>
			<LinkTo>\6276K8_07_COM14\ch14</LinkTo>
		</Item>
		<Item>
			<Offset>17</Offset>
			<StartBit>0</StartBit>
			<BitWidth>8</BitWidth>
			<Type>byte</Type>
			<Name>串口通道07 接收_Byte15</Name>
			<Description>字节，byte15</Description>
			<GroupName>串口通道07</GroupName>
			<IsScaled>0</IsScaled>
			<SystemName>串口</SystemName>
			<Tag>0</Tag>
			<ValueTextList>0</ValueTextList>
			<LinkTo>\6276K8_07_COM14\ch14</LinkTo>
		</Item>
		<Item>
			<Offset>18</Offset>
			<StartBit>0</StartBit>
			<BitWidth>8</BitWidth>
			<Type>byte</Type>
			<Name>串口通道07 接收_Byte16</Name>
			<Description>字节，byte16</Description>
			<GroupName>串口通道07</GroupName>
			<IsScaled>0</IsScaled>
			<SystemName>串口</SystemName>
			<Tag>0</Tag>
			<ValueTextList>0</ValueTextList>
			<LinkTo>\6276K8_07_COM14\ch14</LinkTo>
		</Item>
		<Item>
			<Offset>19</Offset>
			<StartBit>0</StartBit>
			<BitWidth>8</BitWidth>
			<Type>byte</Type>
			<Name>串口通道07 接收_Byte17</Name>
			<Description>字节，byte17</Description>
			<GroupName>串口通道07</GroupName>
			<IsScaled>0</IsScaled>
			<SystemName>串口</SystemName>
			<Tag>0</Tag>
			<ValueTextList>0</ValueTextList>
			<LinkTo>\6276K8_07_COM14\ch14</LinkTo>
		</Item>
	</Data>
</ICDData>

=== qyslamd/ETestStudio/资料收集/Schema/6272T_06_自检_发送.xml
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<ICDData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="IcdSchema.xsd">
	<Name/>
	<Data>
		<Item>
			<Offset>0</Offset>
			<StartBit>0</StartBit>
			<BitWidth>32</BitWidth>
			<Type>dword</Type>
			<Name>A429_IN7(007) 发送数据</Name>
			<Description>发送的32位数据</Description>
			<GroupName>A429_OUT7</GroupName>
			<IsScaled>0</IsScaled>
			<Childs>
				<Item>
					<Offset>0</Offset>
					<StartBit>0</StartBit>
					<BitWidth>8</BitWidth>
					<Type>byte</Type>
					<Name>A429_IN7(007) Label</Name>
					<Description>8bit有效，固定不可修改</Description>
					<GroupName>A429_OUT7</GroupName>
					<IsScaled>0</IsScaled>
					<SystemName>Arinc429</SystemName>
					<Tag>40</Tag>
					<ValueTextList>7</ValueTextList>
					<LinkTo>\6272T_06\ch6</LinkTo>
				</Item>
				<Item>
					<Offset>1</Offset>
					<StartBit>0</StartBit>
					<BitWidth>2</BitWidth>
					<Type>byte</Type>
					<Name>A429_IN7(007) SDI</Name>
					<Description>2bit有效</Description>
					<GroupName>A429_OUT7</GroupName>
					<IsScaled>0</IsScaled>
					<SystemName>Arinc429</SystemName>
					<Tag>0</Tag>
					<ValueTextList>0</ValueTextList>
					<LinkTo>\6272T_06\ch6</LinkTo>
				</Item>
				<Item>
					<Offset>1</Offset>
					<StartBit>2</StartBit>
					<BitWidth>19</BitWidth>
					<Type>int</Type>
					<Name>A429_IN7(007) Data</Name>
					<Description>19bit有效</Description>
					<GroupName>A429_OUT7</GroupName>
					<IsScaled>0</IsScaled>
					<SystemName>Arinc429</SystemName>
					<Tag>0</Tag>
					<ValueTextList>0</ValueTextList>
					<LinkTo>\6272T_06\ch6</LinkTo>
				</Item>
				<Item>
					<Offset>3</Offset>
					<StartBit>5</StartBit>
					<BitWidth>2</BitWidth>
					<Type>byte</Type>
					<Name>A429_IN7(007) SSM</Name>
					<Description>2bit有效</Description>
					<GroupName>A429_OUT7</GroupName>
					<IsScaled>0</IsScaled>
					<SystemName>Arinc429</SystemName>
					<Tag>0</Tag>
					<ValueTextList>0</ValueTextList>
					<LinkTo>\6272T_06\ch6</LinkTo>
				</Item>
				<Item>
					<Offset>3</Offset>
					<StartBit>7</StartBit>
					<BitWidth>1</BitWidth>
					<Type>byte</Type>
					<Name>A429_IN7(007) Parity</Name>
					<Description>1bit有效</Description>
					<GroupName>A429_OUT7</GroupName>
					<IsScaled>0</IsScaled>
					<SystemName>Arinc429</SystemName>
					<Tag>0</Tag>
					<ValueTextList>0</ValueTextList>
					<LinkTo>\6272T_06\ch6</LinkTo>
				</Item>
			</Childs>
			<SystemName>Arinc429</SystemName>
		</Item>
	</Data>
</ICDData>
