=== qyslamd/ETestStudio/资料收集/Schema/IcdSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- edited with XMLSpy v2011 (http://www.altova.com) by JianLuo (Microsoft) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="ICDData">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Name" type="xs:string"/>
				<xs:element name="Data" type="ICDWords"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="ICDWord">
		<xs:sequence>
			<xs:element name="Offset" type="xs:int"/>
			<xs:element name="StartBit" type="xs:int"/>
			<xs:element name="BitWidth" type="xs:int"/>
			<xs:element name="Type" type="xs:string"/>
			<xs:element name="Name" type="xs:string">
				<xs:annotation>
					<xs:documentation>信号名称</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Description" type="xs:string">
				<xs:annotation>
					<xs:documentation>物理信号名称</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="GroupName" type="xs:string" minOccurs="0"/>
			<xs:element name="IsScaled" type="xs:int">
				<xs:annotation>
					<xs:documentation>0/1</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="ScaleA" type="xs:double" minOccurs="0"/>
			<xs:element name="ScaleB" type="xs:double" minOccurs="0"/>
			<xs:element name="Childs" type="ICDWords" minOccurs="0"/>
			<xs:element name="SystemName" type="xs:string" minOccurs="0"/>
			<xs:element name="Min" type="xs:double" minOccurs="0"/>
			<xs:element name="Max" type="xs:double" minOccurs="0"/>
			<xs:element name="Unit" type="xs:string" minOccurs="0"/>
			<xs:element name="Tag" type="xs:int" minOccurs="0"/>
			<xs:element name="ValueTextList" type="xs:string" minOccurs="0"/>
			<xs:element name="ScaleFormula" type="xs:string" default="" minOccurs="0"/>
			<xs:element name="ScaleConveror" type="xs:string" default="" minOccurs="0"/>
			<xs:element name="DefauleValue" minOccurs="0"/>
			<xs:element name="LinkTo" type="xs:string" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ICDWords">
		<xs:sequence maxOccurs="unbounded">
			<xs:element name="Item" type="ICDWord"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== qyslamd/ETestStudio/docs/02-研究/Schema/A429_00_ISI_01_接收_Label317_6272T_00.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<ICDData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="IcdSchema.xsd">
	<Name/>
	<Data>
		<Item>
			<Offset>0</Offset>
			<StartBit>0</StartBit>
			<BitWidth>32</BitWidth>
			<Type>dword</Type>
			<Name>ISI-01#A429_OUT(317) 接收数据</Name>
			<Description>接收的32位数据</Description>
			<GroupName>ISI-01#A429_IN(317)</GroupName>
			<IsScaled>0</IsScaled>
			<Childs>
				<Item>
					<Offset>0</Offset>
					<StartBit>0</StartBit>
					<BitWidth>8</BitWidth>
					<Type>byte</Type>
					<Name>ISI-01#A429_OUT(317) LABEL</Name>
					<Description>8bit有效,八进制,317</Description>
					<GroupName>ISI-01#A429_IN(317)</GroupName>
					<IsScaled>0</IsScaled>
					<SystemName>Arinc429</SystemName>
					<Tag>40</Tag>
					<ValueTextList>207</ValueTextList>
					<LinkTo>\6272T_00\ch0</LinkTo>
				</Item>
				<Item>
					<Offset>1</Offset>
					<StartBit>0</StartBit>
					<BitWidth>2</BitWidth>
					<Type>byte</Type>
					<Name>ISI-01#A429_OUT(317) SDI</Name>
					<Description>2bit有效,内容:All_Call_or_Not_Used=0,Left=1,Right=2,Unused=3</Description>
					<GroupName>ISI-01#A429_IN(317)</GroupName>
					<IsScaled>0</IsScaled>
					<SystemName>Arinc429</SystemName>
					<Tag>0</Tag>
					<ValueTextList>All_Call_or_Not_Used=0,Left=1,Right=2,Unused=3</ValueTextList>
					<LinkTo>\6272T_00\ch0</LinkTo>
				</Item>
				<Item>
					<Offset>1</Offset>
					<StartBit>2</StartBit>
					<BitWidth>19</BitWidth>
					<Type>int</Type>
					<Name>ISI-01#A429_OUT(317) Magnetic_Track_Angle</Name>
					<Description>19bit有效,-180-179.999313</Description>
					<GroupName>ISI-01#A429_IN(317)</GroupName>
					<IsScaled>1</IsScaled>
					<ScaleA>0.000687</ScaleA>
					<SystemName>Arinc429</SystemName>
					<Tag>0</Tag>
					<ValueTextList>0</ValueTextList>
					<LinkTo>\6272T_00\ch0</LinkTo>
				</Item>
				<Item>
					<Offset>3</Offset>
					<StartBit>5</StartBit>
					<BitWidth>2</BitWidth>
					<Type>byte</Type>
					<Name>ISI-01#A429_OUT(317) SSM</Name>
					<Description>2bit有效</Description>
					<GroupName>ISI-01#A429_IN(317)</GroupName>
					<IsScaled>0</IsScaled>
					<SystemName>Arinc429</SystemName>
					<Tag>0</Tag>
					<ValueTextList>0</ValueTextList>
					<LinkTo>\6272T_00\ch0</LinkTo>
				</Item>
				<Item>
					<Offset>3</Offset>
					<StartBit>7</StartBit>
					<BitWidth>1</BitWidth>
					<Type>byte</Type>
					<Name>ISI-01#A429_OUT(317) PARITY</Name>
					<Description>1bit有效</Description>
					<GroupName>ISI-01#A429_IN(317)</GroupName>
					<IsScaled>0</IsScaled>
					<SystemName>Arinc429</SystemName>
					<Tag>0</Tag>
					<ValueTextList>0</ValueTextList>
					<LinkTo>\6272T_00\ch0</LinkTo>
				</Item>
			</Childs>
			<SystemName>Arinc429</SystemName>
		</Item>
	</Data>
</ICDData>

=== qyslamd/ETestStudio/资料收集/Schema/A429_00_ISI_01_接收_Label164_6272T_08.xml
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<ICDData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="IcdSchema.xsd">
	<Name/>
	<Data>
		<Item>
			<Offset>0</Offset>
			<StartBit>0</StartBit>
			<BitWidth>32</BitWidth>
			<Type>dword</Type>
			<Name>ISI-01#A429_OUT(164) 接收数据</Name>
			<Description>接收的32位数据</Description>
			<GroupName>ISI-01#A429_OUT(164)</GroupName>
			<IsScaled>0</IsScaled>
			<Childs>
				<Item>
					<Offset>0</Offset>
					<StartBit>0</StartBit>
					<BitWidth>8</BitWidth>
					<Type>byte</Type>
					<Name>ISI-01#A429_OUT(164) LABEL</Name>
					<Description>8bit有效,八进制,164</Description>
					<GroupName>ISI-01#A429_OUT(164)</GroupName>
					<IsScaled>0</IsScaled>
					<SystemName>Arinc429</SystemName>
					<Tag>40</Tag>
					<ValueTextList>116</ValueTextList>
<<<<<<< HEAD
					<LinkTo>\6272T_08\ch8</LinkTo>
=======
					<LinkTo>6272T_00\ch0</LinkTo>
>>>>>>> 65a49280ce73fa5643f132301f9d69071d289295
				</Item>
				<Item>
					<Offset>1</Offset>
					<StartBit>0</StartBit>
					<BitWidth>2</BitWidth>
					<Type>byte</Type>
					<Name>ISI-01#A429_OUT(164) SDI</Name>
					<Description>2bit有效,内容:ISIS=0</Description>
					<GroupName>ISI-01#A429_OUT(164)</GroupName>
					<IsScaled>0</IsScaled>
					<SystemName>Arinc429</SystemName>
					<Tag>0</Tag>
					<ValueTextList>0</ValueTextList>
<<<<<<< HEAD
					<LinkTo>\6272T_08\ch8</LinkTo>
=======
					<LinkTo>6272T_00\ch0</LinkTo>
>>>>>>> 65a49280ce73fa5643f132301f9d69071d289295
				</Item>
				<Item>
					<Offset>1</Offset>
					<StartBit>2</StartBit>
					<BitWidth>18</BitWidth>
					<Type>int</Type>
					<Name>ISI-01#A429_OUT(164) FIX_Bearing</Name>
					<Description>18bit有效,范围:-180~179.999313</Description>
					<GroupName>ISI-01#A429_OUT(164)</GroupName>
					<IsScaled>1</IsScaled>
					<ScaleA>0.000687</ScaleA>
					<SystemName>Arinc429</SystemName>
					<Unit>°</Unit>
					<Tag>0</Tag>
					<ValueTextList>0</ValueTextList>
<<<<<<< HEAD
					<LinkTo>\6272T_08\ch8</LinkTo>
=======
					<LinkTo>6272T_00\ch0</LinkTo>
>>>>>>> 65a49280ce73fa5643f132301f9d69071d289295
				</Item>
				<Item>
					<Offset>3</Offset>
					<StartBit>4</StartBit>
					<BitWidth>1</BitWidth>
					<Type>byte</Type>
					<Name>ISI-01#A429_OUT(164) PAD</Name>
					<Description>1bit有效</Description>
					<GroupName>ISI-01#A429_OUT(164)</GroupName>
					<IsScaled>0</IsScaled>
					<SystemName>Arinc429</SystemName>
					<Tag>0</Tag>
					<ValueTextList>0</ValueTextList>
<<<<<<< HEAD
					<LinkTo>\6272T_08\ch8</LinkTo>
=======
					<LinkTo>6272T_00\ch0</LinkTo>
>>>>>>> 65a49280ce73fa5643f132301f9d69071d289295
				</Item>
				<Item>
					<Offset>3</Offset>
					<StartBit>5</StartBit>
					<BitWidth>2</BitWidth>
					<Type>byte</Type>
					<Name>ISI-01#A429_OUT(164) SSM</Name>
					<Description>2bit有效</Description>
					<GroupName>ISI-01#A429_OUT(164)</GroupName>
					<IsScaled>0</IsScaled>
					<SystemName>Arinc429</SystemName>
					<Tag>0</Tag>
					<ValueTextList>0</ValueTextList>
<<<<<<< HEAD
					<LinkTo>\6272T_08\ch8</LinkTo>
=======
					<LinkTo>6272T_00\ch0</LinkTo>
>>>>>>> 65a49280ce73fa5643f132301f9d69071d289295
				</Item>
				<Item>
					<Offset>3</Offset>
					<StartBit>7</StartBit>
					<BitWidth>1</BitWidth>
					<Type>byte</Type>
					<Name>ISI-01#A429_OUT(164) PARITY</Name>
					<Description>1bit有效</Description>
					<GroupName>ISI-01#A429_OUT(164)</GroupName>
					<IsScaled>0</IsScaled>
					<SystemName>Arinc429</SystemName>
					<Tag>0</Tag>
					<ValueTextList>0</ValueTextList>
<<<<<<< HEAD
					<LinkTo>\6272T_08\ch8</LinkTo>
=======
					<LinkTo>6272T_00\ch0</LinkTo>
>>>>>>> 65a49280ce73fa5643f132301f9d69071d289295
				</Item>
			</Childs>
			<SystemName>Arinc429</SystemName>
		</Item>
	</Data>
</ICDData>

=== qyslamd/ETestStudio/docs/资料收集/Schema/5272_01_自检_接收.xml
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<ICDData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="IcdSchema.xsd">
	<Name/>
	<Data>
		<Item>
			<Offset>0</Offset>
			<StartBit>0</StartBit>
			<BitWidth>32</BitWidth>
			<Type>dword</Type>
			<Name>A429_OUT2(002) 接收数据</Name>
			<Description>接收的32位数据</Description>
			<GroupName>A429_OUT2</GroupName>
			<IsScaled>0</IsScaled>
			<Childs>
				<Item>
					<Offset>0</Offset>
					<StartBit>0</StartBit>
					<BitWidth>8</BitWidth>
					<Type>byte</Type>
					<Name>A429_OUT2(002) Label</Name>
					<Description>8bit有效，固定不可修改</Description>
					<GroupName>A429_OUT2</GroupName>
					<IsScaled>0</IsScaled>
					<SystemName>Arinc429</SystemName>
					<Tag>40</Tag>
					<ValueTextList>2</ValueTextList>
					<LinkTo>5272_01\ch1</LinkTo>
				</Item>
				<Item>
					<Offset>1</Offset>
					<StartBit>0</StartBit>
					<BitWidth>2</BitWidth>
					<Type>byte</Type>
					<Name>A429_OUT2(002) SDI</Name>
					<Description>2bit有效</Description>
					<GroupName>A429_OUT2</GroupName>
					<IsScaled>0</IsScaled>
					<SystemName>Arinc429</SystemName>
					<Tag>0</Tag>
					<ValueTextList>0</ValueTextList>
					<LinkTo>5272_01\ch1</LinkTo>
				</Item>
				<Item>
					<Offset>1</Offset>
					<StartBit>2</StartBit>
					<BitWidth>19</BitWidth>
					<Type>int</Type>
					<Name>A429_OUT2(002) Data</Name>
					<Description>19bit有效</Description>
					<GroupName>A429_OUT2</GroupName>
					<IsScaled>0</IsScaled>
					<SystemName>Arinc429</SystemName>
					<Tag>0</Tag>
					<ValueTextList>0</ValueTextList>
					<LinkTo>5272_01\ch1</LinkTo>
				</Item>
				<Item>
					<Offset>3</Offset>
					<StartBit>5</StartBit>
					<BitWidth>2</BitWidth>
					<Type>byte</Type>
					<Name>A429_OUT2(002) SSM</Name>
					<Description>2bit有效</Description>
					<GroupName>A429_OUT2</GroupName>
					<IsScaled>0</IsScaled>
					<SystemName>Arinc429</SystemName>
					<Tag>0</Tag>
					<ValueTextList>0</ValueTextList>
					<LinkTo>5272_01\ch1</LinkTo>
				</Item>
				<Item>
					<Offset>3</Offset>
					<StartBit>7</StartBit>
					<BitWidth>1</BitWidth>
					<Type>byte</Type>
					<Name>A429_OUT2(002) Parity</Name>
					<Description>1bit有效</Description>
					<GroupName>A429_OUT2</GroupName>
					<IsScaled>0</IsScaled>
					<SystemName>Arinc429</SystemName>
					<Tag>0</Tag>
					<ValueTextList>0</ValueTextList>
					<LinkTo>5272_01\ch1</LinkTo>
				</Item>
			</Childs>
			<SystemName>Arinc429</SystemName>
		</Item>
	</Data>
</ICDData>

=== qyslamd/ETestStudio/资料收集/Schema/A429_00_ISI_01_接收_Label165_5272_00.xml
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<ICDData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="IcdSchema.xsd">
	<Name/>
	<Data>
		<Item>
			<Offset>0</Offset>
			<StartBit>0</StartBit>
			<BitWidth>32</BitWidth>
			<Type>dword</Type>
			<Name>ISI-01#A429_OUT(165) 接收数据</Name>
			<Description>接收的32位数据</Description>
			<GroupName>ISI-01#A429_OUT(165)</GroupName>
			<IsScaled>0</IsScaled>
			<Childs>
				<Item>
					<Offset>0</Offset>
					<StartBit>0</StartBit>
					<BitWidth>8</BitWidth>
					<Type>byte</Type>
					<Name>ISI-01#A429_OUT(165) LABEL</Name>
					<Description>8bit有效,八进制,165</Description>
					<GroupName>ISI-01#A429_OUT(165)</GroupName>
					<IsScaled>0</IsScaled>
					<SystemName>Arinc429</SystemName>
					<Tag>40</Tag>
					<ValueTextList>117</ValueTextList>
					<LinkTo>5272_00\ch0</LinkTo>
				</Item>
				<Item>
					<Offset>1</Offset>
					<StartBit>0</StartBit>
					<BitWidth>21</BitWidth>
					<Type>int</Type>
					<Name>ISI-01#A429_OUT(165) FIX_Course_Delviation</Name>
					<Description>21bit有效,范围:-20~20</Description>
					<GroupName>ISI-01#A429_OUT(165)</GroupName>
					<IsScaled>1</IsScaled>
					<ScaleA>0.000171661376953125</ScaleA>
					<SystemName>Arinc429</SystemName>
					<Unit>°</Unit>
					<Tag>0</Tag>
					<ValueTextList>0</ValueTextList>
					<LinkTo>5272_00\ch0</LinkTo>
				</Item>
				<Item>
					<Offset>3</Offset>
					<StartBit>5</StartBit>
					<BitWidth>2</BitWidth>
					<Type>byte</Type>
					<Name>ISI-01#A429_OUT(165) SSM</Name>
					<Description>2bit有效</Description>
					<GroupName>ISI-01#A429_OUT(165)</GroupName>
					<IsScaled>0</IsScaled>
					<SystemName>Arinc429</SystemName>
					<Tag>0</Tag>
					<ValueTextList>0</ValueTextList>
					<LinkTo>5272_00\ch0</LinkTo>
				</Item>
				<Item>
					<Offset>3</Offset>
					<StartBit>7</StartBit>
					<BitWidth>1</BitWidth>
					<Type>byte</Type>
					<Name>ISI-01#A429_OUT(165) PARITY</Name>
					<Description>1bit有效</Description>
					<GroupName>ISI-01#A429_OUT(165)</GroupName>
					<IsScaled>0</IsScaled>
					<SystemName>Arinc429</SystemName>
					<Tag>0</Tag>
					<ValueTextList>0</ValueTextList>
					<LinkTo>5272_00\ch0</LinkTo>
				</Item>
			</Childs>
			<SystemName>Arinc429</SystemName>
		</Item>
	</Data>
</ICDData>

=== qyslamd/ETestStudio/tests/icd_utility/data/xml/compat/10AIO2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<ICDData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="IcdSchema.xsd">
	<Name/>
	<Data>
		<Item>
			<Offset>0</Offset>
			<StartBit>0</StartBit>
			<BitWidth>32</BitWidth>
			<Type>dword</Type>
			<Name>电源输出控制</Name>
			<Description>电源输出控制</Description>
			<IsScaled>0</IsScaled>
			<Childs>
				<Item>
					<Offset>0</Offset>
					<StartBit>0</StartBit>
					<BitWidth>2</BitWidth>
					<Type>dword</Type>
					<Name>28V1：输出使能</Name>
					<Description>28V1：输出使能</Description>
					<IsScaled>0</IsScaled>
					<SystemName>电源供电模块</SystemName>
					<ValueTextList>闭合=3,断开=0</ValueTextList>
				</Item>
				<Item>
					<Offset>0</Offset>
					<StartBit>2</StartBit>
					<BitWidth>2</BitWidth>
					<Type>dword</Type>
					<Name>28V2：输出使能</Name>
					<Description>28V2：输出使能</Description>
					<IsScaled>0</IsScaled>
					<SystemName>电源供电模块</SystemName>
					<ValueTextList>闭合=3,断开=0</ValueTextList>
				</Item>
				<Item>
					<Offset>0</Offset>
					<StartBit>4</StartBit>
					<BitWidth>2</BitWidth>
					<Type>dword</Type>
					<Name>5V1：输出使能</Name>
					<Description>5V1：输出使能</Description>
					<IsScaled>0</IsScaled>
					<SystemName>电源供电模块</SystemName>
					<ValueTextList>闭合=3,断开=0</ValueTextList>
				</Item>
				<Item>
					<Offset>0</Offset>
					<StartBit>6</StartBit>
					<BitWidth>2</BitWidth>
					<Type>dword</Type>
					<Name>5V2：输出使能</Name>
					<Description>5V2：输出使能</Description>
					<IsScaled>0</IsScaled>
					<SystemName>电源供电模块</SystemName>
					<ValueTextList>闭合=3,断开=0</ValueTextList>
				</Item>
				<Item>
					<Offset>1</Offset>
					<StartBit>0</StartBit>
					<BitWidth>2</BitWidth>
					<Type>dword</Type>
					<Name>+15V1：输出使能</Name>
					<Description>+15V1：输出使能</Description>
					<IsScaled>0</IsScaled>
					<SystemName>电源供电模块</SystemName>
					<ValueTextList>闭合=3,断开=0</ValueTextList>
				</Item>
				<Item>
					<Offset>1</Offset>
					<StartBit>2</StartBit>
					<BitWidth>2</BitWidth>
					<Type>dword</Type>
					<Name>15V2：输出使能</Name>
					<Description>15V2：输出使能</Description>
					<IsScaled>0</IsScaled>
					<SystemName>电源供电模块</SystemName>
					<ValueTextList>闭合=3,断开=0</ValueTextList>
				</Item>
				<Item>
					<Offset>1</Offset>
					<StartBit>4</StartBit>
					<BitWidth>2</BitWidth>
					<Type>dword</Type>
					<Name>-15V1：输出使能</Name>
					<Description>-15V1：输出使能</Description>
					<IsScaled>0</IsScaled>
					<SystemName>电源供电模块</SystemName>
					<ValueTextList>闭合=3,断开=0</ValueTextList>
				</Item>
				<Item>
					<Offset>1</Offset>
					<StartBit>6</StartBit>
					<BitWidth>2</BitWidth>
					<Type>dword</Type>
					<Name>BRAKE1</Name>
					<Description>电子负载1-1</Description>
					<IsScaled>0</IsScaled>
					<SystemName>制动器电磁阀模块</SystemName>
					<ValueTextList>闭合=3,断开=0</ValueTextList>
				</Item>
				<Item>
					<Offset>2</Offset>
					<StartBit>0</StartBit>
					<BitWidth>2</BitWidth>
					<Type>dword</Type>
					<Name>BRAKE2</Name>
					<Description>电子负载1-1</Description>
					<IsScaled>0</IsScaled>
					<SystemName>制动器电磁阀模块</SystemName>
					<ValueTextList>闭合=3,断开=0</ValueTextList>
				</Item>
				<Item>
					<Offset>2</Offset>
					<StartBit>2</StartBit>
					<BitWidth>2</BitWidth>
					<Type>dword</Type>
					<Name>BRAKE3</Name>
					<Description>电子负载2-1</Description>
					<IsScaled>0</IsScaled>
					<SystemName>制动器电磁阀模块</SystemName>
					<ValueTextList>闭合=3,断开=0</ValueTextList>
				</Item>
				<Item>
					<Offset>2</Offset>
					<StartBit>4</StartBit>
					<BitWidth>2</BitWidth>
					<Type>dword</Type>
					<Name>BRAKE4</Name>
					<Description>电子负载2-1</Description>
					<IsScaled>0</IsScaled>
					<SystemName>制动器电磁阀模块</SystemName>
					<ValueTextList>闭合=3,断开=0</ValueTextList>
				</Item>
			</Childs>
			<LinkTo>\10AIO2\ch0</LinkTo>
		</Item>
	</Data>
</ICDData>

=== qyslamd/ETestStudio/docs/02-研究/Schema/A429_00_ISI_01_接收_Label273_5272_00.xml
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<ICDData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="IcdSchema.xsd">
	<Name/>
	<Data>
		<Item>
			<Offset>0</Offset>
			<StartBit>0</StartBit>
			<BitWidth>32</BitWidth>
			<Type>dword</Type>
			<Name>ISI-01#A429_OUT(273) 接收数据</Name>
			<Description>接收的32位数据</Description>
			<GroupName>ISI-01#A429_OUT(273)</GroupName>
			<IsScaled>0</IsScaled>
			<Childs>
				<Item>
					<Offset>0</Offset>
					<StartBit>0</StartBit>
					<BitWidth>8</BitWidth>
					<Type>byte</Type>
					<Name>ISI-01#A429_OUT(273) LABEL</Name>
					<Description>8bit有效,八进制,273</Description>
					<GroupName>ISI-01#A429_OUT(273)</GroupName>
					<IsScaled>0</IsScaled>
					<SystemName>Arinc429</SystemName>
					<Tag>40</Tag>
					<ValueTextList>187</ValueTextList>
					<LinkTo>5272_00\ch0</LinkTo>
				</Item>
				<Item>
					<Offset>1</Offset>
					<StartBit>0</StartBit>
					<BitWidth>2</BitWidth>
					<Type>byte</Type>
					<Name>ISI-01#A429_OUT(273) SDI</Name>
					<Description>2bit有效,内容:ISIS=0</Description>
					<GroupName>ISI-01#A429_OUT(273)</GroupName>
					<IsScaled>0</IsScaled>
					<SystemName>Arinc429</SystemName>
					<Tag>0</Tag>
					<ValueTextList>0</ValueTextList>
					<LinkTo>5272_00\ch0</LinkTo>
				</Item>
				<Item>
					<Offset>1</Offset>
					<StartBit>2</StartBit>
					<BitWidth>3</BitWidth>
					<Type>byte</Type>
					<Name>ISI-01#A429_OUT(273) PAD1</Name>
					<Description>3bit有效</Description>
					<GroupName>ISI-01#A429_OUT(273)</GroupName>
					<IsScaled>0</IsScaled>
					<SystemName>Arinc429</SystemName>
					<Tag>0</Tag>
					<ValueTextList>0</ValueTextList>
					<LinkTo>5272_00\ch0</LinkTo>
				</Item>
				<Item>
					<Offset>1</Offset>
					<StartBit>5</StartBit>
					<BitWidth>1</BitWidth>
					<Type>byte</Type>
					<Name>ISI-01#A429_OUT(273) NLG_Dnlocked</Name>
					<Description>1bit有效,内容:not_Dnlocked=0,Dnlocked=1</Description>
					<GroupName>ISI-01#A429_OUT(273)</GroupName>
					<IsScaled>0</IsScaled>
					<SystemName>Arinc429</SystemName>
					<Tag>0</Tag>
					<ValueTextList>not_Dnlocked=0,Dnlocked=1</ValueTextList>
					<LinkTo>5272_00\ch0</LinkTo>
				</Item>
				<Item>
					<Offset>1</Offset>
					<StartBit>6</StartBit>
					<BitWidth>15</BitWidth>
					<Type>short</Type>
					<Name>ISI-01#A429_OUT(273) PAD2</Name>
					<Description>15bit有效</Description>
					<GroupName>ISI-01#A429_OUT(273)</GroupName>
					<IsScaled>0</IsScaled>
					<SystemName>Arinc429</SystemName>
					<Tag>0</Tag>
					<ValueTextList>0</ValueTextList>
					<LinkTo>5272_00\ch0</LinkTo>
				</Item>
				<Item>
					<Offset>3</Offset>
					<StartBit>5</StartBit>
					<BitWidth>2</BitWidth>
					<Type>byte</Type>
					<Name>ISI-01#A429_OUT(273) SSM</Name>
					<Description>2bit有效</Description>
					<GroupName>ISI-01#A429_OUT(273)</GroupName>
					<IsScaled>0</IsScaled>
					<SystemName>Arinc429</SystemName>
					<Tag>0</Tag>
					<ValueTextList>0</ValueTextList>
					<LinkTo>5272_00\ch0</LinkTo>
				</Item>
				<Item>
					<Offset>3</Offset>
					<StartBit>7</StartBit>
					<BitWidth>1</BitWidth>
					<Type>byte</Type>
					<Name>ISI-01#A429_OUT(273) PARITY</Name>
					<Description>1bit有效</Description>
					<GroupName>ISI-01#A429_OUT(273)</GroupName>
					<IsScaled>0</IsScaled>
					<SystemName>Arinc429</SystemName>
					<Tag>0</Tag>
					<ValueTextList>0</ValueTextList>
					<LinkTo>5272_00\ch0</LinkTo>
				</Item>
			</Childs>
			<SystemName>Arinc429</SystemName>
		</Item>
	</Data>
</ICDData>

=== qyslamd/ETestStudio/docs/02-研究/Schema/示波器_接收信号质量检测_UsbDP07504_0.xml
<?xml version="1.0" encoding="utf-8"?>
<ICDData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="IcdSchema.xsd">
  <Name />
  <Data>
    <Item>
      <Offset>0</Offset>
      <StartBit>0</StartBit>
      <BitWidth>32</BitWidth>
      <Type>float</Type>
      <Name>示波器 CH1-信号测量上升时间</Name>
      <Description>单位为s</Description>
      <GroupName>CH1</GroupName>
      <IsScaled>0</IsScaled>
      <SystemName>示波器</SystemName>
      <Unit>S</Unit>
      <Tag>0</Tag>
      <LinkTo>\UsbDP07504_0\ch0</LinkTo>
    </Item>
    <Item>
      <Offset>4</Offset>
      <StartBit>0</StartBit>
      <BitWidth>32</BitWidth>
      <Type>float</Type>
      <Name>示波器 CH1-信号测量下降时间</Name>
      <Description>单位为s</Description>
      <GroupName>CH1</GroupName>
      <IsScaled>0</IsScaled>
      <SystemName>示波器</SystemName>
      <Unit>S</Unit>
      <Tag>0</Tag>
      <LinkTo>\UsbDP07504_0\ch0</LinkTo>
    </Item>
    <Item>
      <Offset>8</Offset>
      <StartBit>0</StartBit>
      <BitWidth>32</BitWidth>
      <Type>float</Type>
      <Name>示波器 CH1-信号测量过冲</Name>
      <Description>单位为s</Description>
      <GroupName>CH1</GroupName>
      <IsScaled>0</IsScaled>
      <SystemName>示波器</SystemName>
      <Unit>S</Unit>
      <Tag>0</Tag>
      <LinkTo>\UsbDP07504_0\ch0</LinkTo>
    </Item>
    <Item>
      <Offset>12</Offset>
      <StartBit>0</StartBit>
      <BitWidth>32</BitWidth>
      <Type>float</Type>
      <Name>示波器 CH1-信号测量下降沿过冲</Name>
      <Description>单位为s</Description>
      <GroupName>CH1</GroupName>
      <IsScaled>0</IsScaled>
      <SystemName>示波器</SystemName>
      <Unit>S</Unit>
      <Tag>0</Tag>
      <LinkTo>\UsbDP07504_0\ch0</LinkTo>
    </Item>
    <Item>
      <Offset>16</Offset>
      <StartBit>0</StartBit>
      <BitWidth>32</BitWidth>
      <Type>float</Type>
      <Name>示波器 CH1-信号测量峰峰值</Name>
      <Description>单位为V</Description>
      <GroupName>CH1</GroupName>
      <IsScaled>0</IsScaled>
      <SystemName>示波器</SystemName>
      <Unit>V</Unit>
      <Tag>0</Tag>
      <LinkTo>\UsbDP07504_0\ch0</LinkTo>
    </Item>
  </Data>
</ICDData>

=== qyslamd/ETestStudio/资料收集/Schema/大华电源_过流允许_ComPower_COM1.xml
<?xml version="1.0" encoding="utf-8"?>
<ICDData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="IcdSchema.xsd">
  <Name />
  <Data>
    <Item>
      <Offset>0</Offset>
      <StartBit>0</StartBit>
      <BitWidth>32</BitWidth>
      <Type>dword</Type>
      <Name>ISI-01#直流电源 过流保护功能开关</Name>
      <Description>打开或关闭过流保护功能，参数范围为 ON|OFF。</Description>
      <GroupName>直流电源1</GroupName>
      <IsScaled>0</IsScaled>
      <SystemName>直流电源1</SystemName>
      <Tag>0</Tag>
      <ValueTextList>OFF=0,ON=1</ValueTextList>
      <LinkTo>\ComPower_COM1\ch1</LinkTo>
    </Item>
  </Data>
</ICDData>
