=== qyslamd/ETestStudio/docs/资料收集/Schema/IcdConfig.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="ICDConfig">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Files" type="SchemaFiles"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="SchemaFiles">
		<xs:sequence>
			<xs:element name="FileInfo" type="SchemaFileInfo" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="SchemaFileInfo">
		<xs:sequence>
			<xs:element name="Name" type="xs:string"/>
			<xs:element name="ID" type="xs:int"/>
			<xs:element name="Type" type="xs:int"/>
			<xs:element name="Description" type="xs:string"/>
			<xs:element name="Enable" type="xs:int"/>
			<xs:element name="WordType" type="xs:unsignedInt" default="0">
				<xs:annotation>
					<xs:documentation>保留</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="ByteOrder" type="xs:int">
				<xs:annotation>
					<xs:documentation>大端小端</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Path" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== qyslamd/ETestStudio/tests/icd_utility/data/xml/compat/ICDConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<ICDConfig xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="E:\work_enpht\Projects\EphAutoTest\Source\EphAutoTest.ICD\Schema\IcdConfig.xsd">
	<Files>
		<FileInfo>
			<Name>FDR0</Name>
			<ID>0</ID>
			<Type>1</Type>
			<Description>FDR0</Description>
			<Enable>1</Enable>
			<WordType>0</WordType>
			<ByteOrder>0</ByteOrder>
			<Path>fdr0.xml</Path>
		</FileInfo>
		<FileInfo>
			<Name>DA0_1</Name>
			<ID>1</ID>
			<Type>2</Type>
			<Description>模拟输出</Description>
			<Enable>1</Enable>
			<WordType>0</WordType>
			<ByteOrder>0</ByteOrder>
			<Path>io.xml</Path>
		</FileInfo>
		<FileInfo>
			<Name>AD0</Name>
			<ID>2</ID>
			<Type>1</Type>
			<Description>采集</Description>
			<Enable>1</Enable>
			<WordType>0</WordType>
			<ByteOrder>0</ByteOrder>
			<Path>io2.xml</Path>
		</FileInfo>
		<FileInfo>
			<Name>FDR1</Name>
			<ID>3</ID>
			<Type>1</Type>
			<Description>FDR1</Description>
			<Enable>1</Enable>
			<WordType>0</WordType>
			<ByteOrder>0</ByteOrder>
			<Path>fdr1.xml</Path>
		</FileInfo>
		<FileInfo>
			<Name>DA0_2</Name>
			<ID>4</ID>
			<Type>2</Type>
			<Description>10AIO2</Description>
			<Enable>1</Enable>
			<WordType>0</WordType>
			<ByteOrder>0</ByteOrder>
			<Path>10AIO2.xml</Path>
		</FileInfo>
		<FileInfo>
			<Name>FDR0S</Name>
			<ID>5</ID>
			<Type>2</Type>
			<Description>FDRSender</Description>
			<Enable>1</Enable>
			<WordType>0</WordType>
			<ByteOrder>0</ByteOrder>
			<Path>fdr0_s.xml</Path>
		</FileInfo>
		<FileInfo>
			<Name>FDR0_config</Name>
			<ID>6</ID>
			<Type>4</Type>
			<Description>FDR0_config</Description>
			<Enable>1</Enable>
			<WordType>0</WordType>
			<ByteOrder>0</ByteOrder>
			<Path>fdr0_config.xml</Path>
		</FileInfo>
	</Files>
</ICDConfig>
